import { Department } from '../types';

export const INITIAL_DEPARTMENTS: Department[] = [
  // --- Central Ministries ---
  {
    id: 'DEPT-EDU-01',
    name: 'Department of Higher Education',
    ministry: 'Ministry of Education',
    level: 'Central',
    serviceCount: 9,
    categories: ['Education', 'Financial Assistance'],
    description: 'Oversees collegiate institutions, national scholarships, student welfare grants, and higher education portals.',
    services: [
      'PM Post-Matric Scholarship for Higher Education',
      'Central Sector Scheme of Scholarships for College & University Students',
      'National Means-cum-Merit Scholarship',
      'Vidya Lakshmi Education Loan Facilitation',
      'National Academic Depository (NAD) Certificate Verification'
    ],
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration',
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada', 'Bengali'],
    officialSource: 'https://www.education.gov.in',
    jurisdiction: 'All-India',
  },
  {
    id: 'DEPT-SKILL-02',
    name: 'Ministry of Skill Development & Entrepreneurship',
    ministry: 'Ministry of Skill Development & Entrepreneurship',
    level: 'Central',
    serviceCount: 6,
    categories: ['Employment', 'Education'],
    description: 'Coordinates national skill training missions, apprenticeships, PMKVY certification, and rural youth empowerment schemes.',
    services: [
      'Pradhan Mantri Kaushal Vikas Yojana (PMKVY 4.0)',
      'National Apprenticeship Promotion Scheme (NAPS)',
      'Skill India Digital Hub Certificate Verification',
      'Jan Shikshan Sansthan Community Training'
    ],
    applicationMethod: 'API Assisted',
    integrationStatus: 'Sandbox',
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Marathi', 'Gujarati'],
    officialSource: 'https://www.msde.gov.in',
    jurisdiction: 'All-India',
  },
  {
    id: 'DEPT-LABOUR-03',
    name: 'Ministry of Labour & Employment',
    ministry: 'Ministry of Labour & Employment',
    level: 'Central',
    serviceCount: 8,
    categories: ['Employment', 'Social Welfare'],
    description: 'Manages worker welfare, unorganized sector registration (e-Shram), employment exchanges, and ESIC benefits.',
    services: [
      'e-Shram Universal Social Security Card',
      'National Career Service (NCS) Job Seeker Registration',
      'Pradhan Mantri Shram Yogi Maandhan (PM-SYM Pension)',
      'Employees State Insurance Corporation (ESIC) Health Benefits'
    ],
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration',
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada', 'Bengali', 'Punjabi'],
    officialSource: 'https://labour.gov.in',
    jurisdiction: 'All-India',
  },
  {
    id: 'DEPT-HEALTH-04',
    name: 'National Health Authority (NHA)',
    ministry: 'Ministry of Health & Family Welfare',
    level: 'Central',
    serviceCount: 7,
    categories: ['Healthcare'],
    description: 'Implements Ayushman Bharat PM-JAY cashless hospitalization insurance and Ayushman Bharat Digital Mission (ABDM).',
    services: [
      'Ayushman Bharat PM-JAY Cashless Health Card (₹5 Lakh Cover)',
      'Ayushman Bharat Health Account (ABHA ID Creation)',
      'Pradhan Mantri Surakshit Matritva Abhiyan (PMSMA)',
      'CoWIN Digital Health & Immunization Registry'
    ],
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration',
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada', 'Malayalam', 'Bengali', 'Marathi', 'Gujarati', 'Punjabi', 'Urdu'],
    officialSource: 'https://nha.gov.in',
    jurisdiction: 'All-India',
  },
  {
    id: 'DEPT-AGR-05',
    name: 'Department of Agriculture & Farmers Welfare',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    level: 'Central',
    serviceCount: 9,
    categories: ['Agriculture', 'Financial Assistance'],
    description: 'Orchestrates income support (PM-KISAN), crop insurance (PMFBY), soil testing, agricultural subsidies, and e-NAM markets.',
    services: [
      'PM-KISAN Direct Income Support (₹6,000/yr)',
      'Pradhan Mantri Fasal Bima Yojana (PMFBY Crop Insurance)',
      'Kisan Credit Card (KCC) Subsidized Farm Credit',
      'Soil Health Card & Soil Nutrient Advisory',
      'PM Krishi Sinchayee Yojana (Micro-Irrigation Subsidy)'
    ],
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration',
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada', 'Marathi', 'Punjabi', 'Gujarati'],
    officialSource: 'https://agricoop.nic.in',
    jurisdiction: 'All-India',
  },
  {
    id: 'DEPT-RURAL-06',
    name: 'Ministry of Rural Development',
    ministry: 'Ministry of Rural Development',
    level: 'Central',
    serviceCount: 6,
    categories: ['Social Welfare', 'Housing', 'Employment'],
    description: 'Oversees rural wage employment (MGNREGA), rural housing (PMAY-G), and self-help group livelihood programs (NRLM).',
    services: [
      'MGNREGA 100-Day Wage Employment Job Card',
      'Pradhan Mantri Awas Yojana - Gramin (PMAY-G Housing)',
      'Deendayal Antyodaya Yojana - NRLM Self-Help Group Credit',
      'National Social Assistance Programme (NSAP Rural Pension)'
    ],
    applicationMethod: 'API Assisted',
    integrationStatus: 'Sandbox',
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Bengali', 'Odia'],
    officialSource: 'https://rural.gov.in',
    jurisdiction: 'All-India',
  },
  {
    id: 'DEPT-HOUSING-07',
    name: 'Ministry of Housing & Urban Affairs (MoHUA)',
    ministry: 'Ministry of Housing & Urban Affairs',
    level: 'Central',
    serviceCount: 6,
    categories: ['Housing', 'Municipal Services', 'Financial Assistance'],
    description: 'Implements urban affordable housing (PMAY-U), street vendor micro-credit (PM SVANidhi), and Swachh Bharat urban infrastructure.',
    services: [
      'Pradhan Mantri Awas Yojana (PMAY-Urban) Interest Subsidy',
      'PM SVANidhi Collateral-Free Microcredit for Street Vendors',
      'Swachhata Citizen Grievance Portal',
      'National Urban Livelihoods Mission (DAY-NULM)'
    ],
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration',
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada', 'Marathi'],
    officialSource: 'https://mohua.gov.in',
    jurisdiction: 'All-India',
  },
  {
    id: 'DEPT-WCD-08',
    name: 'Ministry of Women & Child Development',
    ministry: 'Ministry of Women & Child Development',
    level: 'Central',
    serviceCount: 7,
    categories: ['Social Welfare', 'Healthcare'],
    description: 'Drives child protection, maternal nutrition (Poshan Tracker), maternity benefits (PMMVY), and women empowerment centers.',
    services: [
      'Pradhan Mantri Matru Vandana Yojana (PMMVY Maternity Benefit)',
      'Poshan Abhiyaan Child & Maternal Nutrition Support',
      'Beti Bachao Beti Padhao Girl Child Welfare Support',
      'One Stop Centre (Sakhi) Women Safety & Legal Support'
    ],
    applicationMethod: 'API Assisted',
    integrationStatus: 'Demo Integration',
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Bengali', 'Gujarati'],
    officialSource: 'https://wcd.nic.in',
    jurisdiction: 'All-India',
  },
  {
    id: 'DEPT-SOCJUS-09',
    name: 'Ministry of Social Justice & Empowerment',
    ministry: 'Ministry of Social Justice & Empowerment',
    level: 'Central',
    serviceCount: 7,
    categories: ['Social Welfare', 'Education', 'Financial Assistance'],
    description: 'Welfare schemes for SC, OBC, EWS, senior citizens, and de-addiction rehabilitation programs.',
    services: [
      'Post-Matric Scholarship for Scheduled Castes & OBC Students',
      'Rashtriya Vayoshri Yojana (Assistive Devices for Senior Citizens)',
      'Elderline 14567 National Senior Citizen Welfare Helpline',
      'PM Young Achievers Scholarship Award Scheme (PM-YASASVI)'
    ],
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration',
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada'],
    officialSource: 'https://socialjustice.gov.in',
    jurisdiction: 'All-India',
  },
  {
    id: 'DEPT-PWD-10',
    name: 'Department of Empowerment of Persons with Disabilities (DEPwD)',
    ministry: 'Ministry of Social Justice & Empowerment',
    level: 'Central',
    serviceCount: 6,
    categories: ['Identity & Certificates', 'Social Welfare'],
    description: 'Dedicated empowerment of Divyangjan through unique disability identity, assistive aids, and inclusive education.',
    services: [
      'Unique Disability ID (UDID) Card Online Application',
      'ADIP Scheme for Purchase of Assistive Aids and Appliances',
      'Divyangjan Swavalamban Yojana Concessional Loan',
      'Scholarships for Top Class Education for Students with Disabilities'
    ],
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration',
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada', 'Marathi', 'Urdu'],
    officialSource: 'https://swavlambancard.gov.in',
    jurisdiction: 'All-India',
  },
  {
    id: 'DEPT-ITAX-11',
    name: 'Income Tax Department (CBDT)',
    ministry: 'Ministry of Finance',
    level: 'Central',
    serviceCount: 6,
    categories: ['Business & MSME', 'Identity & Certificates'],
    description: 'Administers direct taxation, instant digital PAN generation, Annual Information Statement (AIS), and tax returns.',
    services: [
      'Instant e-PAN Allotment via Aadhaar e-KYC (Zero Fee)',
      'Income Tax e-Filing & Return Verification (ITR 1-4)',
      'Annual Information Statement (AIS / Form 26AS Tax Credit)',
      'PAN-Aadhaar Linking Verification & Correction'
    ],
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration',
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada', 'Bengali', 'Gujarati'],
    officialSource: 'https://eportal.incometax.gov.in',
    jurisdiction: 'All-India',
  },
  {
    id: 'DEPT-MCA-12',
    name: 'Ministry of Corporate Affairs (MCA)',
    ministry: 'Ministry of Corporate Affairs',
    level: 'Central',
    serviceCount: 6,
    categories: ['Business & MSME'],
    description: 'Regulates corporate enterprises, integrated company incorporation (SPICe+), Director Identification Number (DIN), and LLP filings.',
    services: [
      'SPICe+ Integrated Company Incorporation (Name, PAN, TAN, EPFO)',
      'Director Identification Number (DIN / DIR-3 KYC)',
      'Limited Liability Partnership (LLP) Digital Incorporation',
      'MCA Company Master Data Search & Compliance Filing'
    ],
    applicationMethod: 'API Assisted',
    integrationStatus: 'Sandbox',
    languages: ['English', 'Hindi'],
    officialSource: 'https://www.mca.gov.in',
    jurisdiction: 'All-India',
  },
  {
    id: 'DEPT-MSME-13',
    name: 'Ministry of Micro, Small & Medium Enterprises',
    ministry: 'Ministry of Micro, Small & Medium Enterprises',
    level: 'Central',
    serviceCount: 7,
    categories: ['Business & MSME', 'Financial Assistance'],
    description: 'Facilitates MSME registration (Udyam), collateral-free credit (CGTMSE), Prime Minister Employment Generation Programme (PMEGP).',
    services: [
      'Udyam MSME Zero-Fee Digital Registration Certificate',
      'Credit Guarantee Fund Trust for Micro & Small Enterprises (CGTMSE)',
      'Prime Minister Employment Generation Programme (PMEGP Subsidy)',
      'ZED (Zero Defect Zero Effect) Green Manufacturing Certification'
    ],
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration',
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada', 'Gujarati', 'Marathi'],
    officialSource: 'https://udyamregistration.gov.in',
    jurisdiction: 'All-India',
  },
  {
    id: 'DEPT-COMMERCE-14',
    name: 'Department for Promotion of Industry and Internal Trade (DPIIT)',
    ministry: 'Ministry of Commerce & Industry',
    level: 'Central',
    serviceCount: 6,
    categories: ['Business & MSME'],
    description: 'Fosters startups, intellectual property (patents/trademarks), industrial development, and Government e-Marketplace (GeM).',
    services: [
      'Startup India DPIIT Recognition & Tax Exemption Certificate',
      'Import-Export Code (IEC) Digital Issuance (DGFT)',
      'GeM Seller Registration for Government Procurement',
      'Patent & Trademark Fast-Track Examination for Startups'
    ],
    applicationMethod: 'API Assisted',
    integrationStatus: 'Sandbox',
    languages: ['English', 'Hindi'],
    officialSource: 'https://www.startupindia.gov.in',
    jurisdiction: 'All-India',
  },
  {
    id: 'DEPT-CONSUMER-15',
    name: 'Department of Consumer Affairs',
    ministry: 'Ministry of Consumer Affairs, Food & Public Distribution',
    level: 'Central',
    serviceCount: 5,
    categories: ['Grievance & Citizen Services'],
    description: 'Protects consumer rights, consumer court e-filing (e-Daakhil), National Consumer Helpline, and BIS hallmarking standards.',
    services: [
      'National Consumer Helpline (NCH) Grievance Registration',
      'e-Daakhil Online Consumer Court Dispute Filing',
      'BIS Care Hallmark & Standard Quality Verification',
      'National Food Security Ration Card Portability (ONORC)'
    ],
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration',
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada', 'Bengali'],
    officialSource: 'https://consumerhelpline.gov.in',
    jurisdiction: 'All-India',
  },
  {
    id: 'DEPT-FOODPROC-16',
    name: 'Ministry of Food Processing Industries',
    ministry: 'Ministry of Food Processing Industries',
    level: 'Central',
    serviceCount: 4,
    categories: ['Business & MSME', 'Agriculture'],
    description: 'Promotes micro food processing enterprises (PMFME), cold chain logistics subsidies, and agro-processing clusters.',
    services: [
      'PM Formalisation of Micro Food Processing Enterprises (PMFME)',
      'Pradhan Mantri Kisan SAMPADA Yojana Mega Food Park Grant',
      'Operation Greens Tomato-Onion-Potato (TOP) Value Chain Subsidy'
    ],
    applicationMethod: 'Official Portal Routing',
    integrationStatus: 'External Official Service',
    languages: ['English', 'Hindi'],
    officialSource: 'https://mofpi.gov.in',
    jurisdiction: 'All-India',
  },
  {
    id: 'DEPT-ANIMAL-17',
    name: 'Department of Fisheries, Animal Husbandry & Dairying',
    ministry: 'Ministry of Fisheries, Animal Husbandry & Dairying',
    level: 'Central',
    serviceCount: 6,
    categories: ['Agriculture', 'Financial Assistance'],
    description: 'Empowers fishers and livestock owners through PM Matsya Sampada Yojana, dairy infrastructure, and breed improvement.',
    services: [
      'Pradhan Mantri Matsya Sampada Yojana (PMMSY Fishery Grant)',
      'National Livestock Mission Breed Development Subsidy',
      'Dairy Processing and Infrastructure Development Fund (DIDF)',
      'Kisan Credit Card for Animal Husbandry & Dairy Farmers'
    ],
    applicationMethod: 'API Assisted',
    integrationStatus: 'Sandbox',
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Malayalam', 'Bengali'],
    officialSource: 'https://dof.gov.in',
    jurisdiction: 'All-India',
  },
  {
    id: 'DEPT-ENV-18',
    name: 'Ministry of Environment, Forest & Climate Change (MoEFCC)',
    ministry: 'Ministry of Environment, Forest & Climate Change',
    level: 'Central',
    serviceCount: 5,
    categories: ['Business & MSME', 'Municipal Services'],
    description: 'Manages single-window environmental, forest, and wildlife clearances (PARIVESH) and pollution monitoring.',
    services: [
      'PARIVESH Single Window Environmental Clearance (EC/FC/WL)',
      'Central Pollution Control Board (CPCB) Plastic Waste Registration',
      'Battery Waste Management Producer Responsibility Registration'
    ],
    applicationMethod: 'Official Portal Routing',
    integrationStatus: 'External Official Service',
    languages: ['English', 'Hindi'],
    officialSource: 'https://parivesh.nic.in',
    jurisdiction: 'All-India',
  },
  {
    id: 'DEPT-JAL-19',
    name: 'Department of Drinking Water and Sanitation',
    ministry: 'Ministry of Jal Shakti',
    level: 'Central',
    serviceCount: 5,
    categories: ['Municipal Services', 'Agriculture'],
    description: 'Implements rural piped water connections under Jal Jeevan Mission and Swachh Bharat Mission (Gramin).',
    services: [
      'Jal Jeevan Mission Har Ghar Jal Rural Water Supply Tracker',
      'Swachh Bharat Mission Gramin Individual Household Latrine (IHHL) Grant',
      'Atal Bhujal Yojana Groundwater Community Management Support'
    ],
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration',
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada', 'Bengali'],
    officialSource: 'https://jaljeevanmission.gov.in',
    jurisdiction: 'All-India',
  },
  {
    id: 'DEPT-POWER-20',
    name: 'Ministry of Power & MNRE',
    ministry: 'Ministry of Power / MNRE',
    level: 'Central',
    serviceCount: 6,
    categories: ['Housing', 'Agriculture', 'Financial Assistance'],
    description: 'Drives renewable power adoption including PM Surya Ghar free electricity and PM-KUSUM solar agricultural pumps.',
    services: [
      'PM Surya Ghar: Muft Bijli Yojana (Rooftop Solar Subsidy up to ₹78,000)',
      'PM-KUSUM Solar Agriculture Pump Scheme (60% Subsidy)',
      'National Power Consumer Grievance & Energy Efficiency Portal',
      'UJALA Scheme Energy Efficient Appliance Replacement'
    ],
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration',
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada', 'Marathi', 'Gujarati'],
    officialSource: 'https://pmsuryaghar.gov.in',
    jurisdiction: 'All-India',
  },
  {
    id: 'DEPT-TRANSPORT-21',
    name: 'Ministry of Road Transport & Highways (MoRTH)',
    ministry: 'Ministry of Road Transport & Highways',
    level: 'Central',
    serviceCount: 7,
    categories: ['Transport', 'Identity & Certificates'],
    description: 'National portal for driving licences (Sarathi), vehicle registration (Vahan), and national permits.',
    services: [
      'Sarathi Driving Licence Application, Renewal & Address Change',
      'Vahan Vehicle Registration Certificate (RC) & Transfer of Ownership',
      'High Security Registration Plate (HSRP) Online Booking',
      'All-India Tourist Permit (AITP) Online Issuance'
    ],
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration',
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada', 'Marathi', 'Bengali'],
    officialSource: 'https://parivahan.gov.in',
    jurisdiction: 'All-India',
  },
  {
    id: 'DEPT-RAIL-22',
    name: 'Ministry of Railways (Indian Railways)',
    ministry: 'Ministry of Railways',
    level: 'Central',
    serviceCount: 5,
    categories: ['Transport', 'Grievance & Citizen Services'],
    description: 'Coordinates passenger ticketing, RailMadad grievance redressal, railway recruitment, and freight tracking.',
    services: [
      'RailMadad Unified Passenger Grievance & Assistance Portal',
      'IRCTC Next Generation Passenger e-Ticketing Integration',
      'Railway Recruitment Boards (RRB) Centralized Application Portal',
      'Divyangjan Concession e-Ticketing Card'
    ],
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration',
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada', 'Bengali', 'Marathi'],
    officialSource: 'https://railmadad.indianrailways.gov.in',
    jurisdiction: 'All-India',
  },
  {
    id: 'DEPT-AVIA-23',
    name: 'Ministry of Civil Aviation (MoCA)',
    ministry: 'Ministry of Civil Aviation',
    level: 'Central',
    serviceCount: 4,
    categories: ['Transport', 'Grievance & Citizen Services'],
    description: 'Oversees civil air transport, Digi Yatra facial biometric passenger boarding, and AirSewa consumer complaints.',
    services: [
      'AirSewa Passenger Rights & Aviation Grievance Redressal',
      'Digi Yatra Seamless Biometric Airport Enrolment',
      'DigitalSky Drone Pilot & Remote Aircraft Registration'
    ],
    applicationMethod: 'API Assisted',
    integrationStatus: 'Sandbox',
    languages: ['English', 'Hindi'],
    officialSource: 'https://airsewa.gov.in',
    jurisdiction: 'All-India',
  },
  {
    id: 'DEPT-MEA-24',
    name: 'Consular, Passport and Visa Division (CPV)',
    ministry: 'Ministry of External Affairs',
    level: 'Central',
    serviceCount: 6,
    categories: ['Identity & Certificates', 'Transport'],
    description: 'Administers Indian passport issuance (Passport Seva), overseas citizen registrations (OCI), and consular services.',
    services: [
      'Passport Seva Online Application & PSK Appointment Booking',
      'Police Clearance Certificate (PCC) for Emigration/Employment',
      'Overseas Citizen of India (OCI) Card Online Registration',
      'MADAD Consular Grievance Redressal for Indians Abroad'
    ],
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration',
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada', 'Malayalam', 'Punjabi'],
    officialSource: 'https://www.passportindia.gov.in',
    jurisdiction: 'All-India',
  },
  {
    id: 'DEPT-MHA-25',
    name: 'Ministry of Home Affairs (MHA)',
    ministry: 'Ministry of Home Affairs',
    level: 'Central',
    serviceCount: 6,
    categories: ['Grievance & Citizen Services', 'Identity & Certificates'],
    description: 'Coordinates national internal security, National Cyber Crime Reporting Portal, e-FRRO foreigner registrations, and disaster relief.',
    services: [
      'National Cyber Crime Reporting Portal (cybercrime.gov.in)',
      'e-FRRO Foreigners Regional Registration Online',
      'Private Security Agency Licensing (PSARA) Verification',
      'Freedom Fighter Pension (Swatantrata Sainik Samman)'
    ],
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration',
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Bengali', 'Marathi'],
    officialSource: 'https://cybercrime.gov.in',
    jurisdiction: 'All-India',
  },
  {
    id: 'DEPT-ECI-26',
    name: 'Election Commission of India (ECI)',
    ministry: 'Independent Constitutional Authority',
    level: 'Central',
    serviceCount: 5,
    categories: ['Identity & Certificates'],
    description: 'Conducts national and state elections, digital voter card (e-EPIC), voter list corrections, and overseas voter registration.',
    services: [
      'Voter Services Portal (NVSP) New Voter Registration (Form 6)',
      'e-EPIC Digital Voter Identity Card Download',
      'Electoral Roll Correction & Address Shift (Form 8)',
      'Search Name in National Electoral Roll & Polling Station Locator'
    ],
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration',
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada', 'Malayalam', 'Bengali', 'Marathi', 'Gujarati', 'Punjabi', 'Urdu'],
    officialSource: 'https://voters.eci.gov.in',
    jurisdiction: 'All-India',
  },
  {
    id: 'DEPT-DOT-27',
    name: 'Department of Telecommunications (DoT)',
    ministry: 'Ministry of Communications',
    level: 'Central',
    serviceCount: 5,
    categories: ['Grievance & Citizen Services', 'Identity & Certificates'],
    description: 'Protects telecom consumers via Sanchar Saathi (CEIR handset blocking, TAFCOP mobile SIM verification, and fraud prevention).',
    services: [
      'Sanchar Saathi - Block Lost or Stolen Mobile Handset (CEIR)',
      'TAFCOP - Check Active Mobile SIM Connections in Your Name',
      'Chakshu - Report Fraudulent Calls, WhatsApp & SMS Scams',
      'Do Not Disturb (DND) Telemarketing Grievance Registration'
    ],
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration',
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada', 'Bengali'],
    officialSource: 'https://sancharsaathi.gov.in',
    jurisdiction: 'All-India',
  },
  {
    id: 'DEPT-MEITY-28',
    name: 'Ministry of Electronics & Information Technology (MeitY)',
    ministry: 'Ministry of Electronics & Information Technology',
    level: 'Central',
    serviceCount: 7,
    categories: ['Identity & Certificates', 'Grievance & Citizen Services'],
    description: 'Drives Digital India public infrastructure: DigiLocker, UMANG, API Setu, Aadhaar UIDAI, and cyber awareness programs.',
    services: [
      'DigiLocker Universal Digital Document Wallet & Vault',
      'UMANG Multi-Service Citizen Gateway',
      'API Setu Government Data Exchange Framework',
      'Cyber Surakshit Bharat Digital Safety Verification'
    ],
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration',
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada', 'Malayalam', 'Bengali', 'Marathi', 'Gujarati', 'Punjabi', 'Urdu'],
    officialSource: 'https://www.meity.gov.in',
    jurisdiction: 'All-India',
  },
  {
    id: 'DEPT-DEFENCE-29',
    name: 'Department of Ex-Servicemen Welfare',
    ministry: 'Ministry of Defence',
    level: 'Central',
    serviceCount: 5,
    categories: ['Social Welfare', 'Financial Assistance', 'Healthcare'],
    description: 'Welfare for defence veterans, SPARSH digital defence pension, Kendriya Sainik Board grants, and ECHS healthcare.',
    services: [
      'SPARSH Defence Pension Portal & Life Certificate Submission',
      'Kendriya Sainik Board (KSB) Ex-Servicemen Financial Assistance',
      'Ex-Servicemen Contributory Health Scheme (ECHS Smart Card)',
      'Prime Minister Scholarship Scheme for Wards of Ex-Servicemen'
    ],
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration',
    languages: ['English', 'Hindi', 'Punjabi', 'Tamil', 'Telugu'],
    officialSource: 'https://sparsh.defencepension.gov.in',
    jurisdiction: 'All-India',
  },
  {
    id: 'DEPT-PENSION-30',
    name: 'Department of Pension & Pensioners Welfare',
    ministry: 'Ministry of Personnel, Public Grievances and Pensions',
    level: 'Central',
    serviceCount: 5,
    categories: ['Social Welfare', 'Grievance & Citizen Services'],
    description: 'Oversees central pensioner welfare, Bhavishya pension sanctioning tracker, and Jeevan Pramaan biometric life certificates.',
    services: [
      'Jeevan Pramaan Digital Life Certificate (Biometric / Face Auth)',
      'Bhavishya Central Pension Sanction & Payment Tracking System',
      'CPENGRAMS Pension Grievance Redressal Portal',
      'Anubhav Platform for Retiring Government Servants'
    ],
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration',
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Bengali', 'Marathi'],
    officialSource: 'https://jeevanpramaan.gov.in',
    jurisdiction: 'All-India',
  },

  // --- State Government Departments ---
  {
    id: 'DEPT-STATE-REV-31',
    name: 'Department of Revenue (Karnataka)',
    ministry: 'Government of Karnataka',
    level: 'State',
    serviceCount: 11,
    categories: ['Identity & Certificates', 'Land & Property'],
    description: 'Issues statutory certificates (Income, Caste, Residence, Domicile) and manages land records via Bhoomi portal.',
    services: [
      'Income & Asset Certificate (Tehsildar)',
      'Caste & Community Certificate (SC / ST / Category-1 / 2A / 2B / 3A / 3B)',
      'Domicile & Residential Status Certificate',
      'Bhoomi Record of Rights, Tenancy and Crops (RTC / Pahani)',
      'Survival / Family Tree Certificate (Vamsha Vruksha)'
    ],
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration',
    languages: ['Kannada', 'English', 'Hindi'],
    officialSource: 'https://sevasindhu.karnataka.gov.in',
    jurisdiction: 'Karnataka',
  },
  {
    id: 'DEPT-STATE-MAHA-32',
    name: 'Department of Revenue & Forest (Maharashtra)',
    ministry: 'Government of Maharashtra',
    level: 'State',
    serviceCount: 9,
    categories: ['Identity & Certificates', 'Land & Property'],
    description: 'Aaple Sarkar digital state portal managing 7/12 land extract, Domicile, Non-Creamy Layer, and Solvency certificates.',
    services: [
      'Digital 7/12 Extract (Mahabhulekh)',
      'Domicile Certificate (Maharashtra)',
      'Non-Creamy Layer Certificate (OBC / VJNT)',
      'Solvency Certificate for Tenders & Guarantees'
    ],
    applicationMethod: 'API Assisted',
    integrationStatus: 'Sandbox',
    languages: ['Marathi', 'English', 'Hindi'],
    officialSource: 'https://aaplesarkar.mahaonline.gov.in',
    jurisdiction: 'Maharashtra',
  },

  // --- District Administrations ---
  {
    id: 'DEPT-DIST-BLR-33',
    name: 'District Administration (Bengaluru Urban)',
    ministry: 'Government of Karnataka',
    level: 'District',
    serviceCount: 7,
    categories: ['Identity & Certificates', 'Grievance & Citizen Services', 'Land & Property'],
    description: 'Deputy Commissioner & District Magistrate office managing land acquisition, local arms licences, and district grievances.',
    services: [
      'District Collectorate Public Grievance Redressal',
      'Character & Background Verification Certificate',
      'Arms Licence Application & Renewal (NDAL-ALIS)',
      'District Disaster Relief & Ex-Gratia Assistance'
    ],
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration',
    languages: ['English', 'Kannada', 'Hindi'],
    officialSource: 'https://bengaluruurban.nic.in',
    jurisdiction: 'Bengaluru Urban District',
  },

  // --- Municipal & Local Government Bodies ---
  {
    id: 'DEPT-MUNICIPAL-34',
    name: 'Bruhat Bengaluru Mahanagara Palike (BBMP)',
    ministry: 'Urban Development Department (Karnataka)',
    level: 'Municipal',
    serviceCount: 8,
    categories: ['Municipal Services', 'Identity & Certificates', 'Housing'],
    description: 'Municipal corporation for Bengaluru managing birth & death registrations, property tax, trade licences, and civic complaints.',
    services: [
      'Birth Certificate Digital Registration & Download',
      'Death Certificate Digital Registration & Download',
      'Municipal Property Tax SAS Assessment & Payment',
      'Trade Licence New Application & Renewal',
      'FixMyStreet Municipal Complaint & Pothole Grievance'
    ],
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration',
    languages: ['English', 'Kannada', 'Hindi'],
    officialSource: 'https://bbmp.gov.in',
    jurisdiction: 'Bengaluru Metropolitan Area',
  },
  {
    id: 'DEPT-MUNICIPAL-35',
    name: 'Greater Chennai Corporation (GCC)',
    ministry: 'Municipal Administration (Tamil Nadu)',
    level: 'Municipal',
    serviceCount: 7,
    categories: ['Municipal Services', 'Identity & Certificates'],
    description: 'Chennai civic local government managing vital statistics, street sanitation, building planning permissions, and water connections.',
    services: [
      'Birth & Death Registration Portal (GCC)',
      'Chennai Property Tax Payment & Name Transfer',
      'Trade Licence Online Application',
      'Namma Chennai Civic Complaint Redressal'
    ],
    applicationMethod: 'API Assisted',
    integrationStatus: 'Demo Integration',
    languages: ['Tamil', 'English'],
    officialSource: 'https://chennaicorporation.gov.in',
    jurisdiction: 'Chennai City',
  }
];
