import { 
  User,
  CitizenProfile, 
  Service, 
  Department,
  DocumentItem, 
  ConsentItem, 
  Application, 
  AuditLog, 
  ApiIntegration, 
  NotificationItem 
} from '../types';
import { INITIAL_DEPARTMENTS } from './departmentData';
import { EXPANDED_SERVICES } from './servicesData';

export const DEMO_USERS: User[] = [
  {
    id: 'user-ananya',
    name: 'Ananya Sharma',
    email: 'ananya.sharma@demo-govflow.in',
    phone: '+91 98765 43210',
    role: 'citizen',
    personaTitle: 'Student & Degree Candidate (Bengaluru)',
  },
  {
    id: 'user-rajesh',
    name: 'Rajesh Kumar',
    email: 'rajesh.kumar@demo-govflow.in',
    phone: '+91 98451 23456',
    role: 'citizen',
    personaTitle: 'Farmer & Landholder (Mandya)',
  },
  {
    id: 'user-priya',
    name: 'Priya Patel',
    email: 'priya.patel@demo-govflow.in',
    phone: '+91 97312 88990',
    role: 'citizen',
    personaTitle: 'MSME Entrepreneur (Mysuru)',
  },
  {
    id: 'user-officer',
    name: 'Officer K. Venkatesh',
    email: 'k.venkatesh@karnataka.gov.in',
    phone: '+91 94480 11223',
    role: 'officer',
    personaTitle: 'Scrutiny Officer (Revenue & Education Desk)',
  },
  {
    id: 'user-admin',
    name: 'Platform Administrator',
    email: 'admin@govflow.gov.in',
    phone: '+91 99000 00001',
    role: 'sys_admin',
    personaTitle: 'System Admin (Universal Service Registry)',
  }
];

export const INITIAL_CITIZEN_PROFILES: Record<string, CitizenProfile> = {
  'user-ananya': {
    id: 'CIT-KA-2026-0941',
    userId: 'user-ananya',
    name: 'Ananya Sharma',
    email: 'ananya.sharma@demo-govflow.in',
    phone: '+91 98765 43210',
    aadhaarMasked: 'XXXX-XXXX-4921',
    pan: 'ABCDE1234F',
    dob: '2002-08-14',
    gender: 'Female',
    address: {
      line1: '#142, 4th Cross, Malleshwaram',
      district: 'Bengaluru Urban',
      state: 'Karnataka',
      pincode: '560003',
    },
    education: {
      level: 'Undergraduate (B.Tech Computer Science)',
      institution: 'VTU Affiliated Engineering College, Bengaluru',
      passingYear: '2024',
    },
    employment: {
      status: 'Student / Seeking Traineeship',
      occupation: 'Student',
      annualIncome: 240000,
    },
    category: 'OBC',
    profileCompleteness: 78,
  },
  'user-rajesh': {
    id: 'CIT-KA-2026-1482',
    userId: 'user-rajesh',
    name: 'Rajesh Kumar',
    email: 'rajesh.kumar@demo-govflow.in',
    phone: '+91 98451 23456',
    aadhaarMasked: 'XXXX-XXXX-8832',
    pan: 'BNMKP9876Q',
    dob: '1981-05-19',
    gender: 'Male',
    address: {
      line1: 'Village Honaganahalli, Maddur Taluk',
      district: 'Mandya',
      state: 'Karnataka',
      pincode: '571428',
    },
    education: {
      level: 'Higher Secondary (Class 12)',
      institution: 'Govt PU College, Maddur',
      passingYear: '1999',
    },
    employment: {
      status: 'Agricultural Cultivator / Dairy Farmer',
      occupation: 'Farmer',
      annualIncome: 180000,
    },
    category: 'General',
    profileCompleteness: 85,
  },
  'user-priya': {
    id: 'CIT-KA-2026-5521',
    userId: 'user-priya',
    name: 'Priya Patel',
    email: 'priya.patel@demo-govflow.in',
    phone: '+91 97312 88990',
    aadhaarMasked: 'XXXX-XXXX-6119',
    pan: 'PRTYU4321A',
    dob: '1994-11-28',
    gender: 'Female',
    address: {
      line1: 'Plot #45, Hebbal Industrial Area',
      district: 'Mysuru',
      state: 'Karnataka',
      pincode: '570016',
    },
    education: {
      level: 'Postgraduate (MBA Finance)',
      institution: 'University of Mysore',
      passingYear: '2018',
    },
    employment: {
      status: 'Managing Director / Founder',
      occupation: 'Entrepreneur (MSME)',
      annualIncome: 750000,
    },
    category: 'General',
    profileCompleteness: 92,
  }
};

export { INITIAL_DEPARTMENTS };
export const INITIAL_SERVICES: Service[] = EXPANDED_SERVICES;

export const INITIAL_DOCUMENTS: DocumentItem[] = [
  // User Ananya's Documents
  {
    id: 'DOC-AN-001',
    userId: 'user-ananya',
    name: 'Aadhaar Identity Card',
    type: 'Identity Proof',
    status: 'verified',
    issuer: 'UIDAI',
    issueDate: '2016-04-12',
    docNumberMasked: 'XXXX-XXXX-4921',
    source: 'api_setu',
    notes: 'Biometrically verified via UIDAI OTP sandbox',
  },
  {
    id: 'DOC-AN-002',
    userId: 'user-ananya',
    name: 'Permanent Account Number (PAN)',
    type: 'Tax & Identity',
    status: 'verified',
    issuer: 'Income Tax Department (NSDL)',
    issueDate: '2020-11-05',
    docNumberMasked: 'ABCDE****F',
    source: 'digilocker',
    notes: 'Directly synced with NSDL registry',
  },
  {
    id: 'DOC-AN-003',
    userId: 'user-ananya',
    name: '10th & 12th Board Marksheet',
    type: 'Academic Record',
    status: 'verified',
    issuer: 'Karnataka Secondary Education Examination Board',
    issueDate: '2020-07-22',
    docNumberMasked: 'KSEEB-2020-****',
    source: 'digilocker',
    notes: 'Digital signature verified by DigiLocker',
  },
  {
    id: 'DOC-AN-004',
    userId: 'user-ananya',
    name: 'Income Certificate (Tehsildar)',
    type: 'Financial Proof',
    status: 'expiring_soon',
    issuer: 'Revenue Dept, Govt of Karnataka',
    issueDate: '2025-04-01',
    expiryDate: '2026-03-31',
    docNumberMasked: 'RD-0038-****',
    source: 'manual_upload',
    notes: 'Expires in 22 days. Renewal recommended for upcoming schemes.',
  },
  {
    id: 'DOC-AN-005',
    userId: 'user-ananya',
    name: 'Bank Account Passbook (NPCI Seeded)',
    type: 'Banking & DBT',
    status: 'verified',
    issuer: 'State Bank of India (Malleshwaram Branch)',
    issueDate: '2022-01-15',
    docNumberMasked: 'SBIN000****789',
    source: 'api_setu',
    notes: 'Aadhaar seeded for Direct Benefit Transfer (DBT)',
  },

  // User Rajesh's Documents (Farmer)
  {
    id: 'DOC-RJ-001',
    userId: 'user-rajesh',
    name: 'Aadhaar Identity Card',
    type: 'Identity Proof',
    status: 'verified',
    issuer: 'UIDAI',
    issueDate: '2015-02-10',
    docNumberMasked: 'XXXX-XXXX-8832',
    source: 'api_setu',
  },
  {
    id: 'DOC-RJ-002',
    userId: 'user-rajesh',
    name: 'Bhoomi Land Record (RTC / 7/12 Extract)',
    type: 'Land & Agriculture',
    status: 'verified',
    issuer: 'Revenue Department, Govt of Karnataka (Bhoomi)',
    issueDate: '2025-10-12',
    docNumberMasked: 'RTC-MDY-2025-****',
    source: 'digilocker',
    notes: 'Survey No. 42/B, Maddur Hobli (3.2 Acres wetland)',
  },
  {
    id: 'DOC-RJ-003',
    userId: 'user-rajesh',
    name: 'Kisan Credit Card (KCC) Passbook',
    type: 'Banking & DBT',
    status: 'verified',
    issuer: 'Canara Bank (Maddur Branch)',
    issueDate: '2021-08-14',
    docNumberMasked: 'CNRB000****412',
    source: 'api_setu',
    notes: 'Subsidized crop credit linked',
  },

  // User Priya's Documents (MSME Entrepreneur)
  {
    id: 'DOC-PR-001',
    userId: 'user-priya',
    name: 'Aadhaar Identity Card',
    type: 'Identity Proof',
    status: 'verified',
    issuer: 'UIDAI',
    issueDate: '2017-06-18',
    docNumberMasked: 'XXXX-XXXX-6119',
    source: 'api_setu',
  },
  {
    id: 'DOC-PR-002',
    userId: 'user-priya',
    name: 'Enterprise PAN Card',
    type: 'Business Tax Identity',
    status: 'verified',
    issuer: 'Income Tax Department',
    issueDate: '2021-03-20',
    docNumberMasked: 'PRTYU****A',
    source: 'digilocker',
  },
  {
    id: 'DOC-PR-003',
    userId: 'user-priya',
    name: 'GSTIN Registration Certificate',
    type: 'Tax Registration',
    status: 'verified',
    issuer: 'Goods and Services Tax Network (GSTN)',
    issueDate: '2021-04-05',
    docNumberMasked: '29PRTYU****1Z5',
    source: 'api_setu',
  }
];

export const INITIAL_CONSENTS: ConsentItem[] = [
  // Ananya's Consents
  {
    id: 'CON-AN-001',
    userId: 'user-ananya',
    serviceId: 'SRV-EDU-001',
    serviceName: 'PM Post-Matric Scholarship',
    department: 'Ministry of Social Justice & Empowerment',
    requestedData: ['Academic Transcripts', 'Aadhaar Demographics', 'Income Status', 'Bank DBT Account'],
    purpose: 'Verify educational admission and disburse tuition subsidy directly via PFMS.',
    status: 'active',
    grantedAt: '2026-02-14 10:30 AM',
    expiresAt: '2026-12-31',
  },
  {
    id: 'CON-AN-002',
    userId: 'user-ananya',
    serviceId: 'SRV-REV-002',
    serviceName: 'Income Certificate Verification',
    department: 'Department of Revenue, Govt of Karnataka',
    requestedData: ['Electricity Utility Records', 'Ration Card Details'],
    purpose: 'Cross-verify residence address and declare annual household income slab.',
    status: 'active',
    grantedAt: '2026-01-05 02:15 PM',
    expiresAt: '2026-07-05',
  },

  // Rajesh's Consents (Farmer)
  {
    id: 'CON-RJ-001',
    userId: 'user-rajesh',
    serviceId: 'SRV-AGR-004',
    serviceName: 'PM Fasal Bima Yojana',
    department: 'Ministry of Agriculture & Farmers Welfare',
    requestedData: ['Bhoomi RTC Land Extract', 'Aadhaar Demographics', 'Crop Sowing Proof'],
    purpose: 'Underwrite subsidized seasonal crop risk and disburse insurance claims directly to KCC.',
    status: 'active',
    grantedAt: '2026-02-01 09:00 AM',
    expiresAt: '2026-11-30',
  }
];

export const INITIAL_APPLICATIONS: Application[] = [
  // User Ananya's Applications (Student)
  {
    id: 'GF-2026-89421',
    userId: 'user-ananya',
    serviceId: 'SRV-EDU-001',
    serviceName: 'PM Post-Matric Scholarship for Higher Education',
    department: 'Ministry of Social Justice & Empowerment',
    category: 'Education',
    applicantName: 'Ananya Sharma',
    submittedAt: '2026-03-01 09:45 AM',
    updatedAt: '2026-03-05 04:20 PM',
    currentStage: 'Document Validation (DigiLocker)',
    status: 'under_verification',
    priority: 'High',
    stages: [
      { name: 'Application Submitted', status: 'completed', timestamp: '2026-03-01 09:45 AM', note: 'Auto-filled from verified profile' },
      { name: 'Institutional Verification', status: 'completed', timestamp: '2026-03-03 02:10 PM', note: 'Verified by College Registrar office' },
      { name: 'Document Validation (DigiLocker)', status: 'current', timestamp: '2026-03-05 04:20 PM', note: 'API Setu auto-matching marksheet' },
      { name: 'Department Approval', status: 'pending' },
      { name: 'PFMS Direct Benefit Transfer', status: 'pending' },
    ],
    formData: {
      collegeName: 'VTU Engineering College',
      course: 'B.Tech CSE - Final Year',
      annualTuitionFee: 85000,
      hostelResident: false,
    },
    attachedDocuments: ['Aadhaar Card', '10th & 12th Board Marksheet', 'Income Certificate (Tehsildar)', 'Bank Account Passbook (NPCI Seeded)'],
    officerNotes: 'Marksheet matches DigiLocker payload. Awaiting final state quota release.',
  },
  {
    id: 'GF-2026-77319',
    userId: 'user-ananya',
    serviceId: 'SRV-REV-002',
    serviceName: 'Income & Asset Certificate',
    department: 'Department of Revenue, Govt. of Karnataka',
    category: 'Identity & Certificates',
    applicantName: 'Ananya Sharma',
    submittedAt: '2026-02-20 11:15 AM',
    updatedAt: '2026-02-28 01:40 PM',
    currentStage: 'Revenue Inspector Field Verification',
    status: 'department_review',
    priority: 'Normal',
    stages: [
      { name: 'Application Submitted', status: 'completed', timestamp: '2026-02-20 11:15 AM' },
      { name: 'Village Accountant Scrutiny', status: 'completed', timestamp: '2026-02-24 03:30 PM', note: 'Basic documents found order' },
      { name: 'Revenue Inspector Field Verification', status: 'current', timestamp: '2026-02-28 01:40 PM', note: 'Scheduled desk verification' },
      { name: 'Tehsildar Digital Signature', status: 'pending' },
      { name: 'Certificate Issued', status: 'pending' },
    ],
    formData: {
      declaredIncome: 240000,
      familyMembers: 4,
      propertyTaxReceiptNumber: 'BBMP-TAX-2025-9921',
    },
    attachedDocuments: ['Aadhaar Card', 'Electricity Bill'],
    officerNotes: 'Verification in progress with Malleshwaram ward office.',
  },

  // User Rajesh's Applications (Farmer)
  {
    id: 'GF-2026-31984',
    userId: 'user-rajesh',
    serviceId: 'SRV-AGR-004',
    serviceName: 'Pradhan Mantri Fasal Bima Yojana (Crop Insurance)',
    department: 'Ministry of Agriculture & Farmers Welfare',
    category: 'Agriculture',
    applicantName: 'Rajesh Kumar',
    submittedAt: '2026-02-15 10:20 AM',
    updatedAt: '2026-02-18 03:30 PM',
    currentStage: 'Policy Cover Issued',
    status: 'approved',
    priority: 'High',
    stages: [
      { name: 'Policy Enrolment', status: 'completed', timestamp: '2026-02-15 10:20 AM' },
      { name: 'Land Record API Match (Bhoomi)', status: 'completed', timestamp: '2026-02-16 11:00 AM', note: 'Verified against Survey No 42/B' },
      { name: 'Premium Subsidization Approved', status: 'completed', timestamp: '2026-02-18 03:30 PM' },
      { name: 'Active Season Monitoring', status: 'completed', timestamp: '2026-02-18 03:30 PM' },
    ],
    formData: {
      cropType: 'Paddy / Sugarcane',
      cultivatedAreaAcres: 3.2,
      kccAccountNumber: 'CNRB000****412',
    },
    attachedDocuments: ['Aadhaar Identity Card', 'Bhoomi Land Record (RTC / 7/12 Extract)', 'Kisan Credit Card (KCC) Passbook'],
    officerNotes: 'Bhoomi RTC land parcel matched. Subsidized policy bond generated.',
  },

  // User Priya's Applications (MSME Entrepreneur)
  {
    id: 'GF-2026-55210',
    userId: 'user-priya',
    serviceId: 'SRV-MSME-005',
    serviceName: 'Udyam MSME Registration & Priority Lending Certificate',
    department: 'Ministry of Micro, Small and Medium Enterprises',
    category: 'Business & MSME',
    applicantName: 'Priya Patel',
    submittedAt: '2026-02-28 02:15 PM',
    updatedAt: '2026-02-28 02:30 PM',
    currentStage: 'Udyam Digital Certificate Issued',
    status: 'completed',
    priority: 'Normal',
    stages: [
      { name: 'Aadhaar & PAN Verification', status: 'completed', timestamp: '2026-02-28 02:15 PM' },
      { name: 'Enterprise Data Form Fill', status: 'completed', timestamp: '2026-02-28 02:20 PM' },
      { name: 'API Sync with CBDT & GSTN', status: 'completed', timestamp: '2026-02-28 02:25 PM' },
      { name: 'Instant Digital Udyam Certificate Issued', status: 'completed', timestamp: '2026-02-28 02:30 PM', note: 'Certificate: UDYAM-KR-03-009812' },
    ],
    formData: {
      enterpriseName: 'Mysore Precision Tech Private Limited',
      panNumber: 'PRTYU****A',
      gstin: '29PRTYU****1Z5',
      investmentPlantMachinery: 4500000,
    },
    attachedDocuments: ['Aadhaar Identity Card', 'Enterprise PAN Card', 'GSTIN Registration Certificate'],
    officerNotes: 'Automated verification successful via CBDT-GSTN bridge.',
  }
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'AUD-901',
    userId: 'user-ananya',
    timestamp: '2026-03-05 04:20 PM',
    actor: 'GovFlow System (Automated)',
    actorRole: 'System Orchestrator',
    action: 'DigiLocker Document Validation',
    service: 'PM Post-Matric Scholarship',
    applicationId: 'GF-2026-89421',
    result: 'Success',
    details: 'Digital signature on 12th marksheet verified against KSEEB public key repository.',
  },
  {
    id: 'AUD-902',
    userId: 'user-ananya',
    timestamp: '2026-03-04 11:15 AM',
    actor: 'Officer K. Venkatesh (ID: OFF-882)',
    actorRole: 'Department Officer',
    action: 'Application Stage Advanced',
    service: 'Income & Asset Certificate',
    applicationId: 'GF-2026-77319',
    result: 'Manual Review',
    details: 'Forwarded to Malleshwaram ward revenue inspector after initial document audit.',
  },
  {
    id: 'AUD-903',
    userId: 'user-rajesh',
    timestamp: '2026-02-18 03:30 PM',
    actor: 'Agriculture Dept Sanction Officer',
    actorRole: 'Department Officer',
    action: 'Crop Insurance Sanction Approved',
    service: 'PM Fasal Bima Yojana',
    applicationId: 'GF-2026-31984',
    result: 'Success',
    details: 'Verified land record with Bhoomi registry and approved subsidized premium bond.',
  }
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  // Ananya's Notifications
  {
    id: 'NOTIF-AN-001',
    userId: 'user-ananya',
    title: 'Document Expiration Alert',
    message: 'Your Income Certificate issued by Revenue Dept expires in 22 days. Renew to avoid disruption in scholarship schemes.',
    type: 'warning',
    timestamp: '2 hours ago',
    read: false,
    link: '/documents',
  },
  {
    id: 'NOTIF-AN-002',
    userId: 'user-ananya',
    title: 'Scholarship Stage Advanced',
    message: 'Application GF-2026-89421 has passed institutional verification and is now under DigiLocker document matching.',
    type: 'info',
    timestamp: '1 day ago',
    read: false,
    link: '/applications/GF-2026-89421',
  },

  // Rajesh's Notifications (Farmer)
  {
    id: 'NOTIF-RJ-001',
    userId: 'user-rajesh',
    title: 'Crop Insurance Policy Bond Active',
    message: 'Policy bond for application GF-2026-31984 is active. Paddy crop at Honaganahalli is protected for Kharif season.',
    type: 'success',
    timestamp: '3 days ago',
    read: false,
    link: '/applications/GF-2026-31984',
  },

  // Priya's Notifications (MSME)
  {
    id: 'NOTIF-PR-001',
    userId: 'user-priya',
    title: 'Udyam Certificate Ready',
    message: 'Udyam registration certificate generated successfully for Mysore Precision Tech Pvt Ltd. Ready for priority credit.',
    type: 'success',
    timestamp: '1 week ago',
    read: true,
    link: '/applications/GF-2026-55210',
  }
];

export const INITIAL_INTEGRATIONS: ApiIntegration[] = [
  {
    id: 'INT-001',
    name: 'DigiLocker National Gateway',
    type: 'National Digital Document Vault',
    endpoint: 'https://api.digitallocker.gov.in/v3/sandbox',
    status: 'connected',
    health: 'Operational',
    latency: 38,
    lastSync: 'Just now (Continuous)',
    totalRequests: 14820,
    errorRate: '0.02%',
  },
  {
    id: 'INT-002',
    name: 'API Setu (Open API Platform)',
    type: 'Government API Exchange',
    endpoint: 'https://apisetu.gov.in/v2/exchange/sandbox',
    status: 'connected',
    health: 'Operational',
    latency: 42,
    lastSync: '2 minutes ago',
    totalRequests: 28940,
    errorRate: '0.04%',
  },
  {
    id: 'INT-003',
    name: 'Karnataka Seva Sindhu Gateway',
    type: 'State Service Integration Adapter',
    endpoint: 'https://sevasindhu.karnataka.gov.in/adapter/v1',
    status: 'connected',
    health: 'Operational',
    latency: 55,
    lastSync: '5 minutes ago',
    totalRequests: 8430,
    errorRate: '0.11%',
  },
  {
    id: 'INT-004',
    name: 'MoHUA Urban Housing Exchange',
    type: 'Central Department API Adapter',
    endpoint: 'https://pmaymis.gov.in/api/v2/mock',
    status: 'sandbox',
    health: 'Operational',
    latency: 68,
    lastSync: '12 minutes ago',
    totalRequests: 3240,
    errorRate: '0.20%',
  },
  {
    id: 'INT-005',
    name: 'Municipal CRS Civil Registration Registry',
    type: 'Local Urban Body Adapter',
    endpoint: 'https://crsorgi.gov.in/api/birth-death/v1',
    status: 'sandbox',
    health: 'Operational',
    latency: 74,
    lastSync: '18 minutes ago',
    totalRequests: 1910,
    errorRate: '0.15%',
  }
];

export const LIFE_EVENTS_CONFIG = [
  {
    id: 'new-child',
    title: 'New Child',
    emoji: '👶',
    tagline: 'Welcoming a new life into your family',
    description: 'Coordinate birth registration, newborn health immunization benefits, and maternity support from day one.',
    recommendedServices: ['SRV-MUNI-007', 'SRV-HLT-006'],
  },
  {
    id: 'starting-college',
    title: 'Starting College',
    emoji: '🎓',
    tagline: 'Higher education & career launchpad',
    description: 'One-click discover scholarships, tuition fee subsidies, education certificates, and hostel benefits.',
    recommendedServices: ['SRV-EDU-001', 'SRV-REV-002', 'SRV-EMP-009'],
  },
  {
    id: 'looking-for-employment',
    title: 'Looking for Employment',
    emoji: '💼',
    tagline: 'Skill training, career services & jobs',
    description: 'Register with national career portals, discover free vocational certifications, and apply for apprentice roles.',
    recommendedServices: ['SRV-EMP-009', 'SRV-MSME-005', 'SRV-TRN-010'],
  },
  {
    id: 'buying-home',
    title: 'Buying or Building a Home',
    emoji: '🏠',
    tagline: 'Housing assistance, land registry & utility hookups',
    description: 'Check CLSS home loan subsidies, property title deed verification, and municipal water/power meters.',
    recommendedServices: ['SRV-HOU-003', 'SRV-REV-002'],
  },
  {
    id: 'farmer-support',
    title: 'Farmer Support',
    emoji: '🌾',
    tagline: 'Crop insurance, agricultural credit & subsidies',
    description: 'Pradhan Mantri Fasal Bima Yojana, Kisan Credit Cards, soil health testing, and farm equipment grants.',
    recommendedServices: ['SRV-AGR-004'],
  },
  {
    id: 'senior-citizen',
    title: 'Senior Citizen',
    emoji: '👵',
    tagline: 'Pensions, healthcare & social security',
    description: 'Old-age pension enrolment, Ayushman senior health benefits, and senior citizen concession cards.',
    recommendedServices: ['SRV-PEN-008', 'SRV-HLT-006'],
  }
];

// Explicitly isolated Sandbox Evaluation Data for SIH Hackathon & Evaluation Demos
// Never used as production default users
export const SANDBOX_EVALUATION_DATA = {
  users: DEMO_USERS,
  profiles: INITIAL_CITIZEN_PROFILES,
  documents: INITIAL_DOCUMENTS,
  consents: INITIAL_CONSENTS,
  applications: INITIAL_APPLICATIONS,
  notifications: INITIAL_NOTIFICATIONS,
};
