import { Service } from '../types';

export const EXPANDED_SERVICES: Service[] = [
  // --- EDUCATION ---
  {
    id: 'SRV-EDU-001',
    name: 'PM Post-Matric Scholarship for Higher Education',
    department: 'Department of Higher Education',
    ministry: 'Ministry of Education',
    category: 'Education',
    level: 'Central',
    state: 'All-India',
    description: 'Financial assistance for meritorious students belonging to marginalized or lower-income households pursuing post-matriculation or technical degree courses.',
    eligibilitySummary: 'Enrolled in recognized degree, family annual income <= ₹2.5 Lakhs, domicile of India.',
    eligibilityRules: [
      {
        id: 'rule-edu-1',
        field: 'annualIncome',
        label: 'Family Annual Income (₹)',
        type: 'number',
        max: 250000,
        explanation: 'Annual family income must not exceed ₹2,50,000 from all sources.',
      },
      {
        id: 'rule-edu-2',
        field: 'category',
        label: 'Social Category',
        type: 'select',
        options: ['OBC', 'SC', 'ST', 'EWS', 'General'],
        explanation: 'Eligible for OBC, SC, ST, and EWS categories under national guidelines.',
      },
      {
        id: 'rule-edu-3',
        field: 'isEnrolledDegree',
        label: 'Currently Enrolled in Higher Secondary or Degree College?',
        type: 'boolean',
        requiredValue: true,
        explanation: 'Applicant must be an active student in an accredited institution.',
      }
    ],
    requiredDocuments: ['Aadhaar Card', 'Income Certificate', '10th & 12th Marksheet', 'College Admission Fee Receipt', 'Bank Passbook'],
    workflowStages: ['Application Submitted', 'Institutional Verification', 'Document Validation (DigiLocker)', 'Department Approval', 'PFMS Direct Benefit Transfer'],
    expectedTimeline: '14 - 21 working days',
    fee: '₹0 (Free)',
    officialSource: 'scholarships.gov.in',
    lastVerified: '2026-03-01',
    tags: ['scholarship', 'student', 'tuition', 'college', 'financial support', 'education'],
    lifeEvents: ['Starting College', 'Looking for Employment'],
    isOnline: true,
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada', 'Bengali'],
    matchScore: 94,
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration',
    withdrawalPolicy: {
      allowed: true,
      allowedStatuses: ['draft', 'submitted', 'under_verification', 'department_review'],
      reasonRequired: true,
      reasonOptions: [
        'No longer required',
        'Submitted by mistake',
        'Information needs correction',
        'Applying for another service',
        'Other'
      ],
      warningMessage: 'Withdrawing this scholarship application cancels all pending institutional scrutiny and PFMS payment queuing. Withdrawal cannot be undone.',
      allowRestoration: false,
      notifyDepartment: true,
    }
  },
  {
    id: 'SRV-EDU-002',
    name: 'Central Sector Scheme of Scholarships for College and University Students',
    department: 'Department of Higher Education',
    ministry: 'Ministry of Education',
    category: 'Education',
    level: 'Central',
    state: 'All-India',
    description: 'Direct scholarship grant of ₹12,000 to ₹20,000 annually for top 20th percentile board examination rankers from lower and middle income families.',
    eligibilitySummary: 'Top 20th percentile in 12th Board, annual family income <= ₹4.5 Lakhs, regular full-time course.',
    eligibilityRules: [
      {
        id: 'rule-cs-1',
        field: 'annualIncome',
        label: 'Family Annual Income (₹)',
        type: 'number',
        max: 450000,
        explanation: 'Must not exceed ₹4,50,000 per annum.',
      },
      {
        id: 'rule-cs-2',
        field: 'boardPercentile',
        label: 'Class 12th Board Percentile',
        type: 'number',
        min: 80,
        explanation: 'Must have scored in top 20th percentile of respective State/CBSE Board.',
      }
    ],
    requiredDocuments: ['Aadhaar Card', 'Class 12th Board Marksheet', 'Income Certificate', 'College Bonafide Certificate', 'Bank Account Details'],
    workflowStages: ['Online Registration', 'College Principal Verification', 'State Nodal Officer Review', 'PFMS Direct Bank Credit'],
    expectedTimeline: '15 - 30 working days',
    fee: '₹0 (Free)',
    officialSource: 'scholarships.gov.in',
    lastVerified: '2026-02-20',
    tags: ['college', 'scholarship', 'merit', 'university', 'undergraduate', 'education'],
    lifeEvents: ['Starting College'],
    isOnline: true,
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Bengali'],
    matchScore: 89,
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration'
  },
  {
    id: 'SRV-EDU-003',
    name: 'Vidya Lakshmi Education Loan Scheme (Govt. Interest Subsidy CSIS)',
    department: 'Department of Higher Education',
    ministry: 'Ministry of Education',
    category: 'Education',
    level: 'Central',
    state: 'All-India',
    description: 'Full interest subsidy during the moratorium period (course + 1 year) on educational loans up to ₹7.5 Lakhs for students with parental income up to ₹4.5 Lakhs.',
    eligibilitySummary: 'Admitted to NAAC/NBA accredited higher educational institution, family annual income <= ₹4.5 Lakhs.',
    eligibilityRules: [
      {
        id: 'rule-vl-1',
        field: 'annualIncome',
        label: 'Family Annual Income (₹)',
        type: 'number',
        max: 450000,
        explanation: 'Parental income ceiling of ₹4.5 Lakh per annum for Central Sector Interest Subsidy (CSIS).',
      }
    ],
    requiredDocuments: ['Aadhaar Card', 'PAN Card of Student & Co-borrower', 'Admission Letter with Fee Structure', 'Income Certificate issued by Tehsildar'],
    workflowStages: ['Application Submitted', 'Bank Branch Appraisal', 'Canara Bank Nodal Verification', 'Subsidy Credit to Loan Account'],
    expectedTimeline: '20 - 30 working days',
    fee: '₹0 (Free)',
    officialSource: 'vidyalakshmi.co.in',
    lastVerified: '2026-02-18',
    tags: ['loan', 'education loan', 'interest subsidy', 'college fees', 'higher education'],
    lifeEvents: ['Starting College'],
    isOnline: true,
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada'],
    matchScore: 85,
    applicationMethod: 'API Assisted',
    integrationStatus: 'Sandbox'
  },

  // --- SKILL DEVELOPMENT & LABOUR ---
  {
    id: 'SRV-SKILL-004',
    name: 'Pradhan Mantri Kaushal Vikas Yojana (PMKVY 4.0 Certification)',
    department: 'Ministry of Skill Development & Entrepreneurship',
    ministry: 'Ministry of Skill Development & Entrepreneurship',
    category: 'Employment',
    level: 'Central',
    state: 'All-India',
    description: 'Free industry-aligned short-term skill training, assessment, and government certification with monetary reward and placement assistance.',
    eligibilitySummary: 'Indian citizen aged 15-45, school/college dropouts or unemployed youth seeking technical skills.',
    eligibilityRules: [
      {
        id: 'rule-pmkvy-1',
        field: 'age',
        label: 'Applicant Age',
        type: 'number',
        min: 15,
        max: 45,
        explanation: 'Open to youth aged 15 to 45 years.',
      }
    ],
    requiredDocuments: ['Aadhaar Card', 'Educational Qualification Certificate', 'Bank Account Passbook'],
    workflowStages: ['Center Enrolment', 'Theory & Practical Training', 'Third-Party Assessment', 'National Skill Certificate Issued'],
    expectedTimeline: '30 - 90 days depending on course module',
    fee: '₹0 (100% Govt Funded)',
    officialSource: 'skillindiadigital.gov.in',
    lastVerified: '2026-03-02',
    tags: ['skill', 'pmkvy', 'vocational', 'training', 'job', 'certification'],
    lifeEvents: ['Looking for Employment'],
    isOnline: true,
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Marathi', 'Gujarati'],
    matchScore: 91,
    applicationMethod: 'API Assisted',
    integrationStatus: 'Sandbox'
  },
  {
    id: 'SRV-LABOUR-005',
    name: 'e-Shram National Database for Unorganised Workers (UAN Card)',
    department: 'Ministry of Labour & Employment',
    ministry: 'Ministry of Labour & Employment',
    category: 'Social Welfare',
    level: 'Central',
    state: 'All-India',
    description: 'Universal digital identity card for unorganised workers with ₹2 Lakh accidental insurance cover and direct portability of national welfare schemes.',
    eligibilitySummary: 'Unorganised worker aged 16-59, not a member of EPFO/ESIC, not an income tax payee.',
    eligibilityRules: [
      {
        id: 'rule-es-1',
        field: 'age',
        label: 'Worker Age',
        type: 'number',
        min: 16,
        max: 59,
        explanation: 'Worker must be between 16 and 59 years old.',
      },
      {
        id: 'rule-es-2',
        field: 'isEpfoMember',
        label: 'Is applicant an active member of EPFO or ESIC?',
        type: 'boolean',
        requiredValue: false,
        explanation: 'Must be working in the unorganised sector without EPFO/ESIC coverage.',
      }
    ],
    requiredDocuments: ['Aadhaar Card with linked mobile number', 'Bank Account Passbook (Aadhaar Seeded)'],
    workflowStages: ['Aadhaar OTP e-KYC', 'Occupation Details Entry', 'Instant UAN e-Shram Card Generated'],
    expectedTimeline: 'Instant (10 minutes)',
    fee: '₹0 (Free)',
    officialSource: 'eshram.gov.in',
    lastVerified: '2026-03-04',
    tags: ['eshram', 'worker', 'labour', 'social security', 'unorganised', 'uan'],
    lifeEvents: ['Looking for Employment', 'Farmer Support'],
    isOnline: true,
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada', 'Bengali', 'Punjabi'],
    matchScore: 95,
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration'
  },
  {
    id: 'SRV-LABOUR-006',
    name: 'National Career Service (NCS) Job Seeker Registration',
    department: 'Ministry of Labour & Employment',
    ministry: 'Ministry of Labour & Employment',
    category: 'Employment',
    level: 'Central',
    state: 'All-India',
    description: 'Free pan-India portal connecting job seekers with verified government and private vacancies, job fairs, career counseling, and skill training.',
    eligibilitySummary: 'Indian citizens aged 18+ seeking career opportunities or apprenticeship openings.',
    eligibilityRules: [
      {
        id: 'rule-ncs-1',
        field: 'age',
        label: 'Applicant Age',
        type: 'number',
        min: 18,
        explanation: 'Applicant must be at least 18 years of age.',
      }
    ],
    requiredDocuments: ['Aadhaar Card / Official National ID', 'Resume / Academic Certificates'],
    workflowStages: ['Online Registration', 'DigiLocker Document Sync', 'Job Matching & Interview Notifications'],
    expectedTimeline: 'Instant Profile Activation',
    fee: '₹0 (Free)',
    officialSource: 'ncs.gov.in',
    lastVerified: '2026-02-25',
    tags: ['jobs', 'employment', 'ncs', 'career', 'recruitment', 'government jobs'],
    lifeEvents: ['Looking for Employment'],
    isOnline: true,
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Marathi'],
    matchScore: 92,
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration'
  },

  // --- HEALTHCARE ---
  {
    id: 'SRV-HLT-007',
    name: 'Ayushman Bharat National Health Protection Card (PM-JAY)',
    department: 'National Health Authority (NHA)',
    ministry: 'Ministry of Health & Family Welfare',
    category: 'Healthcare',
    level: 'Central',
    state: 'All-India',
    description: 'Cashless healthcare cover up to ₹5,00,000 per family per year for secondary and tertiary care hospitalization across empanelled public and private hospitals.',
    eligibilitySummary: 'Families identified under SECC 2011 deprivation criteria or state-recognized low-income cards.',
    eligibilityRules: [
      {
        id: 'rule-pmjay-1',
        field: 'hasRationOrAadhaar',
        label: 'Holder of National Food Security Card (Ration Card) or SECC listed?',
        type: 'boolean',
        requiredValue: true,
        explanation: 'Enrolment is based on National Food Security database or SECC deprivation.',
      }
    ],
    requiredDocuments: ['Aadhaar Card', 'Ration Card / BPL Card', 'Active Mobile Number for OTP'],
    workflowStages: ['e-KYC Verification via UIDAI', 'Database Eligibility Match', 'Beneficiary Approval by NHA', 'Ayushman PVC / Digital Card Issued'],
    expectedTimeline: '2 - 4 business days',
    fee: '₹0 (Free)',
    officialSource: 'pmjay.gov.in',
    lastVerified: '2026-03-01',
    tags: ['health', 'hospital', 'cashless', 'medical', 'ayushman', 'pmjay'],
    lifeEvents: ['Having a Child', 'Senior Citizen Welfare'],
    isOnline: true,
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada', 'Bengali'],
    matchScore: 96,
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration'
  },
  {
    id: 'SRV-HLT-008',
    name: 'Ayushman Bharat Health Account (ABHA 14-Digit Digital Health ID)',
    department: 'National Health Authority (NHA)',
    ministry: 'Ministry of Health & Family Welfare',
    category: 'Healthcare',
    level: 'Central',
    state: 'All-India',
    description: 'Unique 14-digit digital health identifier enabling citizens to store, access, and share electronic health records and lab prescriptions securely with doctors.',
    eligibilitySummary: 'Open to all Indian citizens with Aadhaar or Driving Licence verification.',
    eligibilityRules: [
      {
        id: 'rule-abha-1',
        field: 'hasAadhaarOrDL',
        label: 'Possesses valid Aadhaar Card or Driving Licence?',
        type: 'boolean',
        requiredValue: true,
        explanation: 'Authentication via Aadhaar OTP or Driving Licence is required.',
      }
    ],
    requiredDocuments: ['Aadhaar Card with linked mobile number'],
    workflowStages: ['Aadhaar OTP Authentication', 'Create ABHA Address (@abdm)', 'Instant ABHA Digital Card Download'],
    expectedTimeline: 'Instant (2 minutes)',
    fee: '₹0 (Free)',
    officialSource: 'abha.abdm.gov.in',
    lastVerified: '2026-03-05',
    tags: ['abha', 'health id', 'medical records', 'digital health', 'ayushman'],
    lifeEvents: ['Having a Child', 'Senior Citizen Welfare'],
    isOnline: true,
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada', 'Malayalam', 'Bengali', 'Marathi', 'Gujarati', 'Punjabi', 'Urdu'],
    matchScore: 98,
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration'
  },

  // --- AGRICULTURE & FARMERS ---
  {
    id: 'SRV-AGR-009',
    name: 'PM-KISAN Samman Nidhi (Direct Farmer Income Support ₹6,000/yr)',
    department: 'Department of Agriculture & Farmers Welfare',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    category: 'Agriculture',
    level: 'Central',
    state: 'All-India',
    description: 'Direct financial assistance of ₹6,000 per year transferred in three equal installments of ₹2,000 directly into the bank accounts of cultivable landholding farmer families.',
    eligibilitySummary: 'Small and marginal farmer families holding cultivable land in their names.',
    eligibilityRules: [
      {
        id: 'rule-pmk-1',
        field: 'hasAgriculturalLand',
        label: 'Does the farmer family own cultivable agricultural land in official records?',
        type: 'boolean',
        requiredValue: true,
        explanation: 'Land must be registered in the applicant’s name in state land records.',
      },
      {
        id: 'rule-pmk-2',
        field: 'isInstitutionalFarmer',
        label: 'Is applicant an institutional landholder, MP, MLA, or high income tax payee?',
        type: 'boolean',
        requiredValue: false,
        explanation: 'Constitutional post holders and income tax payees are excluded under PM-KISAN rules.',
      }
    ],
    requiredDocuments: ['Aadhaar Card', 'Land Record (RTC / 7/12 Extract / Khatauni)', 'Aadhaar Seeded Bank Account Details'],
    workflowStages: ['Online Registration', 'State Land Record API Verification', 'District Agriculture Officer Approval', 'Direct Benefit Transfer (DBT)'],
    expectedTimeline: 'Next seasonal installment release',
    fee: '₹0 (Free)',
    officialSource: 'pmkisan.gov.in',
    lastVerified: '2026-03-02',
    tags: ['pmkisan', 'farmer', 'kisan', 'agriculture', 'income support', 'dbt'],
    lifeEvents: ['Farmer Support'],
    isOnline: true,
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada', 'Marathi', 'Punjabi', 'Gujarati'],
    matchScore: 97,
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration'
  },
  {
    id: 'SRV-AGR-010',
    name: 'Pradhan Mantri Fasal Bima Yojana (PMFBY Crop Insurance)',
    department: 'Department of Agriculture & Farmers Welfare',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    category: 'Agriculture',
    level: 'Central',
    state: 'All-India',
    description: 'Comprehensive crop insurance protection against non-preventable natural calamities, drought, floods, pest attacks, and post-harvest losses at subsidized premiums.',
    eligibilitySummary: 'All farmers cultivating notified crops in notified areas including sharecroppers and tenant farmers.',
    eligibilityRules: [
      {
        id: 'rule-pmfby-1',
        field: 'isFarmer',
        label: 'Cultivates agricultural land (owner or tenant)?',
        type: 'boolean',
        requiredValue: true,
        explanation: 'Applicant must be an active cultivator of notified crop land.',
      }
    ],
    requiredDocuments: ['Aadhaar Card', 'Land Record (RTC / Patta / 7/12)', 'Sowing Certificate / Declaration', 'Bank Account Passbook'],
    workflowStages: ['Policy Enrolment', 'Land Record API Match', 'Premium Payment', 'Instant Policy Cover Issued', 'Satellite Weather Claim Trigger'],
    expectedTimeline: 'Instant policy cover; seasonal claim settlement',
    fee: '1.5% to 2% subsidized premium',
    officialSource: 'pmfby.gov.in',
    lastVerified: '2026-02-28',
    tags: ['crop insurance', 'farmer', 'pmfby', 'weather damage', 'agriculture', 'kharif', 'rabi'],
    lifeEvents: ['Farmer Support'],
    isOnline: true,
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Marathi', 'Kannada'],
    matchScore: 96,
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration'
  },
  {
    id: 'SRV-AGR-011',
    name: 'Kisan Credit Card (KCC) Subsidized Agricultural Credit',
    department: 'Department of Agriculture & Farmers Welfare',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    category: 'Agriculture',
    level: 'Central',
    state: 'All-India',
    description: 'Concessional crop loans up to ₹3 Lakhs at an effective 4% interest rate (with timely repayment prompt interest subvention) for seeds, fertilizers, and farm equipment.',
    eligibilitySummary: 'All farmers (individual/joint borrowers, tenant farmers, self-help groups, animal husbandry and fisheries cultivators).',
    eligibilityRules: [
      {
        id: 'rule-kcc-1',
        field: 'isCultivator',
        label: 'Is applicant an active agricultural or dairy cultivator?',
        type: 'boolean',
        requiredValue: true,
        explanation: 'Applicant must be engaged in farming, livestock, or aquaculture.',
      }
    ],
    requiredDocuments: ['Aadhaar Card', 'Land Record / RTC Extract', 'Crop Sowing Pattern Declaration', 'Bank Account Details'],
    workflowStages: ['Online Application', 'Bank Manager Land Scrutiny', 'KCC Sanction & RuPay Kisan Card Disbursal'],
    expectedTimeline: '14 working days',
    fee: '₹0 Processing fee up to ₹3 Lakhs',
    officialSource: 'agricoop.nic.in',
    lastVerified: '2026-02-15',
    tags: ['kcc', 'kisan credit card', 'farm loan', 'subsidy', 'fertilizer loan', 'agriculture'],
    lifeEvents: ['Farmer Support'],
    isOnline: true,
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada'],
    matchScore: 93,
    applicationMethod: 'API Assisted',
    integrationStatus: 'Live Integration'
  },
  {
    id: 'SRV-AGR-012',
    name: 'Soil Health Card Scheme (Free Soil Nutrient & Fertilizer Testing)',
    department: 'Department of Agriculture & Farmers Welfare',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    category: 'Agriculture',
    level: 'Central',
    state: 'All-India',
    description: 'Periodic soil testing providing customized crop-wise recommendations of macro and micro-nutrients to reduce fertilizer expenses and boost farm yields.',
    eligibilitySummary: 'All agricultural landowners and cultivators in India.',
    eligibilityRules: [
      {
        id: 'rule-shc-1',
        field: 'hasFarmPlot',
        label: 'Has identified farm plot with survey number?',
        type: 'boolean',
        requiredValue: true,
        explanation: 'Soil sample collection is geotagged to the survey plot number.',
      }
    ],
    requiredDocuments: ['Aadhaar Card', 'Farm Survey Plot Details (RTC / Patta Number)'],
    workflowStages: ['Soil Sample Collection', 'Lab Testing (12 Parameters)', 'Digital Soil Health Card Generated'],
    expectedTimeline: '10 - 15 working days',
    fee: '₹0 (100% Free Service)',
    officialSource: 'soilhealth.dac.gov.in',
    lastVerified: '2026-02-10',
    tags: ['soil', 'soil health card', 'fertilizer', 'agriculture', 'crop yield', 'farming'],
    lifeEvents: ['Farmer Support'],
    isOnline: true,
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada', 'Marathi'],
    matchScore: 90,
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration'
  },
  {
    id: 'SRV-AGR-013',
    name: 'Pradhan Mantri Matsya Sampada Yojana (PMMSY Fishery Subsidies)',
    department: 'Department of Fisheries, Animal Husbandry & Dairying',
    ministry: 'Ministry of Fisheries, Animal Husbandry & Dairying',
    category: 'Agriculture',
    level: 'Central',
    state: 'All-India',
    description: 'Financial assistance of up to 60% for fish farming pond construction, biofloc systems, recirculating aquaculture (RAS), and motorized fishing boats.',
    eligibilitySummary: 'Fishers, fish farmers, self-help groups, and fisheries cooperatives.',
    eligibilityRules: [
      {
        id: 'rule-pmmsy-1',
        field: 'isFisher',
        label: 'Involved in aquaculture, marine fishing, or inland fisheries?',
        type: 'boolean',
        requiredValue: true,
        explanation: 'Targeted support for traditional fishers and aquaculture entrepreneurs.',
      }
    ],
    requiredDocuments: ['Aadhaar Card', 'Land/Waterbody Lease Document', 'Detailed Project Report (DPR)', 'Bank Passbook'],
    workflowStages: ['Project Proposal Submission', 'District Fisheries Officer Technical Appraisal', 'State Approval & Subsidy Disbursal'],
    expectedTimeline: '30 - 45 working days',
    fee: '₹0 (Free Application)',
    officialSource: 'pmmsy.dof.gov.in',
    lastVerified: '2026-02-12',
    tags: ['fisheries', 'aquaculture', 'fish farming', 'pmmsy', 'subsidy'],
    lifeEvents: ['Farmer Support', 'Starting a Business'],
    isOnline: true,
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Malayalam', 'Bengali'],
    matchScore: 88,
    applicationMethod: 'API Assisted',
    integrationStatus: 'Sandbox'
  },

  // --- HOUSING & RURAL DEVELOPMENT ---
  {
    id: 'SRV-HOU-014',
    name: 'Pradhan Mantri Awas Yojana (PMAY-Urban Interest Subsidy CLSS)',
    department: 'Ministry of Housing and Urban Affairs (MoHUA)',
    ministry: 'Ministry of Housing & Urban Affairs',
    category: 'Housing',
    level: 'Central',
    state: 'All-India',
    description: 'Credit Linked Subsidy Scheme (CLSS) providing upfront interest subsidy on home loans for first-time urban home buyers from EWS, LIG, and MIG categories.',
    eligibilitySummary: 'First-time home buyer, family does not own a pucca house anywhere in India, household income within designated slabs.',
    eligibilityRules: [
      {
        id: 'rule-pmay-1',
        field: 'noPuccaHouse',
        label: 'Does applicant or family own any pucca house in India?',
        type: 'boolean',
        requiredValue: false,
        explanation: 'Must be a first-time home buyer without existing residential property.',
      },
      {
        id: 'rule-pmay-2',
        field: 'annualIncome',
        label: 'Family Annual Income (₹)',
        type: 'number',
        max: 1800000,
        explanation: 'Applicable for EWS (<=₹3L), LIG (<=₹6L), MIG-I (<=₹12L), and MIG-II (<=₹18L).',
      }
    ],
    requiredDocuments: ['Aadhaar Card', 'PAN Card', 'Income Tax Returns / Form 16', 'Bank Statement (6 months)', 'Property Agreement Draft'],
    workflowStages: ['Online Registration', 'Primary Lending Institution (PLI) Appraisal', 'Central Nodal Agency (CNA) Review', 'Subsidy Credit to Loan Account'],
    expectedTimeline: '30 - 45 working days',
    fee: '₹0 (Free)',
    officialSource: 'pmay-urban.gov.in',
    lastVerified: '2026-01-20',
    tags: ['housing', 'pmay', 'home loan', 'subsidy', 'apartment', 'urban'],
    lifeEvents: ['Buying or Building a Home'],
    isOnline: true,
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada'],
    matchScore: 84,
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Sandbox'
  },
  {
    id: 'SRV-HOU-015',
    name: 'Pradhan Mantri Awas Yojana - Gramin (PMAY-G Rural Housing Grant ₹1.2 Lakh)',
    department: 'Ministry of Rural Development',
    ministry: 'Ministry of Rural Development',
    category: 'Housing',
    level: 'Central',
    state: 'All-India',
    description: 'Direct financial assistance of ₹1,20,000 in plains and ₹1,30,000 in hilly states to homeless and kutcha-house dwelling rural families for pucca house construction.',
    eligibilitySummary: 'Identified under Socio-Economic and Caste Census (SECC 2011) or Awaas+ list without existing pucca house.',
    eligibilityRules: [
      {
        id: 'rule-pmayg-1',
        field: 'isRuralResident',
        label: 'Resident of rural village / gram panchayat?',
        type: 'boolean',
        requiredValue: true,
        explanation: 'Scheme is exclusively for rural gram panchayat residents.',
      }
    ],
    requiredDocuments: ['Aadhaar Card', 'MGNREGA Job Card Number', 'Bank Account Passbook', 'Land Possession Document'],
    workflowStages: ['Gram Sabha Priority List', 'Geotagged Kutcha House Verification', 'Staged Fund Transfers (Foundation, Lintel, Roof)', 'Pucca House Handover'],
    expectedTimeline: '3 to 6 months staged construction',
    fee: '₹0 (Free)',
    officialSource: 'pmayg.nic.in',
    lastVerified: '2026-02-14',
    tags: ['rural housing', 'pmay-g', 'house grant', 'village home', 'housing'],
    lifeEvents: ['Buying or Building a Home'],
    isOnline: true,
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Bengali'],
    matchScore: 91,
    applicationMethod: 'API Assisted',
    integrationStatus: 'Sandbox'
  },

  // --- BUSINESS & MSME ---
  {
    id: 'SRV-MSME-016',
    name: 'Udyam MSME Digital Registration Certificate (Instant & Zero Fee)',
    department: 'Ministry of Micro, Small & Medium Enterprises',
    ministry: 'Ministry of Micro, Small & Medium Enterprises',
    category: 'Business & MSME',
    level: 'Central',
    state: 'All-India',
    description: 'Zero-cost paperless digital registration for Micro, Small, and Medium enterprises with priority lending eligibility, subsidy on patents, and electricity concessions.',
    eligibilitySummary: 'Any enterprise meeting investment and turnover criteria for Micro, Small, or Medium classification.',
    eligibilityRules: [
      {
        id: 'rule-msme-1',
        field: 'hasPANAndGST',
        label: 'Has valid PAN and GSTIN (if applicable for turnover)?',
        type: 'boolean',
        requiredValue: true,
        explanation: 'PAN is mandatory for Udyam Registration auto-fetch from CBDT.',
      }
    ],
    requiredDocuments: ['Aadhaar Card of Entrepreneur', 'PAN Card of Enterprise', 'Bank Account Details', 'Business Activity Description'],
    workflowStages: ['Aadhaar & PAN Verification', 'Enterprise Data Form Fill', 'API Sync with CBDT & GSTN', 'Instant Digital Udyam Certificate Issued'],
    expectedTimeline: 'Instant (15 minutes digital generation)',
    fee: '₹0 (Free - Govt. official portal has no fee)',
    officialSource: 'udyamregistration.gov.in',
    lastVerified: '2026-03-02',
    tags: ['business', 'msme', 'startup', 'udyam', 'enterprise', 'gst'],
    lifeEvents: ['Starting a Business'],
    isOnline: true,
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada', 'Gujarati', 'Marathi'],
    matchScore: 97,
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration'
  },
  {
    id: 'SRV-MSME-017',
    name: 'SPICe+ Integrated Digital Company Incorporation (MCA-21)',
    department: 'Ministry of Corporate Affairs (MCA)',
    ministry: 'Ministry of Corporate Affairs',
    category: 'Business & MSME',
    level: 'Central',
    state: 'All-India',
    description: 'Single-window digital form for company name reservation, incorporation (COI), DIN allotment, PAN, TAN, EPFO, ESIC, and corporate bank account opening.',
    eligibilitySummary: 'Any 2 or more directors/shareholders forming a Private Limited or One Person Company in India.',
    eligibilityRules: [
      {
        id: 'rule-spice-1',
        field: 'hasDigitalSignature',
        label: 'Proposed directors possess valid Class-3 Digital Signature Certificate (DSC)?',
        type: 'boolean',
        requiredValue: true,
        explanation: 'Class 3 DSC is statutory requirement for online ROC filing.',
      }
    ],
    requiredDocuments: ['PAN & Aadhaar of all Directors', 'Proof of Registered Office Address (Utility Bill + NOC)', 'Draft Memorandum & Articles of Association (MoA / AoA)'],
    workflowStages: ['Name Approval (Part A)', 'Incorporation & Statutory Registrations (Part B)', 'ROC Scrutiny', 'Certificate of Incorporation Issued'],
    expectedTimeline: '3 - 5 business days',
    fee: 'Govt ROC Stamp Duty varies by state',
    officialSource: 'mca.gov.in',
    lastVerified: '2026-02-28',
    tags: ['company registration', 'pvt ltd', 'mca', 'incorporation', 'startup', 'business'],
    lifeEvents: ['Starting a Business'],
    isOnline: true,
    languages: ['English', 'Hindi'],
    matchScore: 90,
    applicationMethod: 'API Assisted',
    integrationStatus: 'Sandbox'
  },
  {
    id: 'SRV-MSME-018',
    name: 'Startup India DPIIT Recognition & Income Tax Exemption (Section 80-IAC)',
    department: 'Department for Promotion of Industry and Internal Trade (DPIIT)',
    ministry: 'Ministry of Commerce & Industry',
    category: 'Business & MSME',
    level: 'Central',
    state: 'All-India',
    description: 'Official national recognition for innovative startups providing 3-year income tax holiday, angel tax exemption, patent fast-tracking, and government tender exemptions.',
    eligibilitySummary: 'Entity incorporated as Pvt Ltd or LLP within past 10 years, annual turnover under ₹100 Crores, working towards innovation or scalable business model.',
    eligibilityRules: [
      {
        id: 'rule-start-1',
        field: 'turnoverUnder100Cr',
        label: 'Annual turnover has not exceeded ₹100 Crores in any previous financial year?',
        type: 'boolean',
        requiredValue: true,
        explanation: 'Turnover ceiling of ₹100 Cr applies under DPIIT startup definition.',
      }
    ],
    requiredDocuments: ['Certificate of Incorporation (ROC)', 'Brief Pitch Deck / Business Scalability Note', 'Patent / Trademark details (if applicable)'],
    workflowStages: ['Online Application Submission', 'DPIIT Expert Committee Review', 'Recognition Certificate & Tax Exemption Order Issued'],
    expectedTimeline: '5 - 10 working days',
    fee: '₹0 (Free)',
    officialSource: 'startupindia.gov.in',
    lastVerified: '2026-02-22',
    tags: ['startup', 'dpiit', 'tax holiday', 'angel tax', 'innovation', 'funding'],
    lifeEvents: ['Starting a Business'],
    isOnline: true,
    languages: ['English', 'Hindi'],
    matchScore: 92,
    applicationMethod: 'API Assisted',
    integrationStatus: 'Sandbox'
  },

  // --- STATUTORY CERTIFICATES ---
  {
    id: 'SRV-CERT-019',
    name: 'Birth Certificate Digital Registration & Official Extract',
    department: 'Bruhat Bengaluru Mahanagara Palike (BBMP) / Municipal Authority',
    ministry: 'Ministry of Home Affairs / Local Municipal Corporation',
    category: 'Identity & Certificates',
    level: 'Local',
    state: 'Karnataka',
    description: 'Official statutory registration and digitally signed birth certificate extraction under the Registration of Births and Deaths Act.',
    eligibilitySummary: 'Child born within municipal or panchayat jurisdiction with hospital institutional discharge record.',
    eligibilityRules: [
      {
        id: 'rule-birth-1',
        field: 'hasHospitalDischarge',
        label: 'Possesses hospital institutional birth discharge summary or Form-1 report?',
        type: 'boolean',
        requiredValue: true,
        explanation: 'Institutional birth report from authorized hospital is mandatory.',
      }
    ],
    requiredDocuments: ['Hospital Birth Discharge Summary', 'Aadhaar Card of Parents', 'Marriage Proof of Parents'],
    workflowStages: ['Application Submitted', 'Sub-Registrar of Vital Statistics Verification', 'Digital Signature of Registrar', 'Certificate Available for Download'],
    expectedTimeline: '3 - 5 working days',
    fee: '₹5 (Within 21 days free; nominal fee thereafter)',
    officialSource: 'bbmp.gov.in / crsorgi.gov.in',
    lastVerified: '2026-03-01',
    tags: ['birth certificate', 'child birth', 'municipal', 'identity', 'certificates'],
    lifeEvents: ['Having a Child'],
    isOnline: true,
    languages: ['English', 'Kannada', 'Hindi'],
    matchScore: 96,
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration'
  },
  {
    id: 'SRV-CERT-020',
    name: 'Income & Asset Certificate (State Revenue Department)',
    department: 'Department of Revenue (Karnataka)',
    ministry: 'Government of Karnataka',
    category: 'Identity & Certificates',
    level: 'State',
    state: 'Karnataka',
    description: 'Statutory certificate issued by the Tehsildar certifying the annual income of an individual and their family for government schemes, admissions, and fee concessions.',
    eligibilitySummary: 'Legal resident of Karnataka with verified local address and income documentation.',
    eligibilityRules: [
      {
        id: 'rule-inc-1',
        field: 'residentState',
        label: 'Current Resident State',
        type: 'select',
        options: ['Karnataka', 'Tamil Nadu', 'Telangana', 'Andhra Pradesh', 'Maharashtra', 'Other'],
        requiredValue: 'Karnataka',
        explanation: 'Must be a legal resident of Karnataka for state tehsildar jurisdiction.',
      }
    ],
    requiredDocuments: ['Aadhaar Card', 'Salary Slip / Income Affidavit', 'Recent Electricity Bill', 'Ration Card (if applicable)'],
    workflowStages: ['Application Submitted', 'Village Accountant Scrutiny', 'Revenue Inspector Field Verification', 'Tehsildar Digital Signature', 'Certificate Issued'],
    expectedTimeline: '7 - 10 working days',
    fee: '₹25 (State Portal User Fee)',
    officialSource: 'sevasindhu.karnataka.gov.in',
    lastVerified: '2026-02-15',
    tags: ['income certificate', 'revenue', 'tehsildar', 'e-district', 'caste', 'fee waiver'],
    lifeEvents: ['Starting College', 'Looking for Employment', 'Buying or Building a Home'],
    isOnline: true,
    languages: ['English', 'Kannada', 'Hindi'],
    matchScore: 93,
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration',
    withdrawalPolicy: {
      allowed: true,
      allowedStatuses: ['draft', 'submitted', 'under_verification'],
      reasonRequired: true,
      reasonOptions: [
        'No longer required',
        'Submitted by mistake',
        'Information needs correction',
        'Other'
      ],
      warningMessage: 'Withdrawal is permitted only prior to field verification. Once in desk review, statutory protocol applies.',
      allowRestoration: false,
      notifyDepartment: true,
    }
  },
  {
    id: 'SRV-CERT-021',
    name: 'Caste & Community Certificate (SC / ST / OBC / Category-1)',
    department: 'Department of Revenue (Karnataka)',
    ministry: 'Government of Karnataka',
    category: 'Identity & Certificates',
    level: 'State',
    state: 'Karnataka',
    description: 'Statutory certification of caste and category membership issued by the Revenue Sub-Divisional Officer / Tehsildar for affirmative action benefits.',
    eligibilitySummary: 'Belongs to officially recognized Scheduled Caste, Scheduled Tribe, or Backward Category with ancestral school/revenue proof.',
    eligibilityRules: [
      {
        id: 'rule-caste-1',
        field: 'hasAncestralProof',
        label: 'Possesses father/ancestor school transfer certificate or revenue record mentioning caste?',
        type: 'boolean',
        requiredValue: true,
        explanation: 'Ancestral record is statutory evidence of community membership.',
      }
    ],
    requiredDocuments: ['Aadhaar Card', 'Applicant / Father School Transfer Certificate (TC)', 'Family Tree Affidavit (Vamsha Vruksha)', 'Ration Card'],
    workflowStages: ['Application Lodged', 'Revenue Inspector Inquiry', 'Tehsildar Digital Endorsement', 'Barcoded Certificate Issued'],
    expectedTimeline: '10 - 15 working days',
    fee: '₹25 (Portal User Fee)',
    officialSource: 'sevasindhu.karnataka.gov.in',
    lastVerified: '2026-02-25',
    tags: ['caste certificate', 'obc', 'sc', 'st', 'reservation', 'revenue', 'tahsildar'],
    lifeEvents: ['Starting College', 'Looking for Employment'],
    isOnline: true,
    languages: ['English', 'Kannada', 'Hindi'],
    matchScore: 94,
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration'
  },
  {
    id: 'SRV-CERT-022',
    name: 'Domicile & Residential Status Certificate',
    department: 'Department of Revenue (Karnataka)',
    ministry: 'Government of Karnataka',
    category: 'Identity & Certificates',
    level: 'State',
    state: 'Karnataka',
    description: 'Certifies continuous residence in the state for a minimum prescribed period (usually 7-10 years) for government admissions and state recruitment.',
    eligibilitySummary: 'Continuous stay in Karnataka for minimum 7 continuous years.',
    eligibilityRules: [
      {
        id: 'rule-dom-1',
        field: 'continuousResidenceYears',
        label: 'Number of continuous years residing in State',
        type: 'number',
        min: 7,
        explanation: 'Minimum 7 years of continuous residence in the state is required.',
      }
    ],
    requiredDocuments: ['Aadhaar Card', 'School Study Certificates (7 continuous years)', 'Electricity / Water Utility Bills', 'Property Tax Receipt / Rent Agreement'],
    workflowStages: ['Application Submitted', 'Police / Revenue Verification', 'Tehsildar Digital Signature', 'Certificate Available Online'],
    expectedTimeline: '7 - 14 working days',
    fee: '₹25',
    officialSource: 'sevasindhu.karnataka.gov.in',
    lastVerified: '2026-02-26',
    tags: ['domicile', 'residence certificate', 'nativity', 'state quota', 'revenue'],
    lifeEvents: ['Starting College', 'Looking for Employment'],
    isOnline: true,
    languages: ['English', 'Kannada', 'Hindi'],
    matchScore: 91,
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration'
  },
  {
    id: 'SRV-CERT-023',
    name: 'Unique Disability ID (UDID) Card & Disability Certificate',
    department: 'Department of Empowerment of Persons with Disabilities (DEPwD)',
    ministry: 'Ministry of Social Justice & Empowerment',
    category: 'Identity & Certificates',
    level: 'Central',
    state: 'All-India',
    description: 'National disability identity card providing single-point verification for railway concessions, assistive aids, educational scholarships, and tax benefits.',
    eligibilitySummary: 'Person with benchmark disability (40% or higher) evaluated by Government Medical Board.',
    eligibilityRules: [
      {
        id: 'rule-udid-1',
        field: 'hasDisabilityAssessment',
        label: 'Evaluated by District Medical Authority or Government Hospital?',
        type: 'boolean',
        requiredValue: true,
        explanation: 'Medical board assessment of disability percentage is required.',
      }
    ],
    requiredDocuments: ['Aadhaar Card', 'Passport Photo', 'Medical Board Assessment Certificate / Hospital Records'],
    workflowStages: ['Online Registration', 'District Hospital CMO Verification & Slot Booking', 'Medical Board Assessment', 'UDID Card Dispatched to Address'],
    expectedTimeline: '15 - 30 working days',
    fee: '₹0 (Free)',
    officialSource: 'swavlambancard.gov.in',
    lastVerified: '2026-03-01',
    tags: ['disability certificate', 'udid', 'divyangjan', 'medical board', 'concessions'],
    lifeEvents: ['Senior Citizen Welfare', 'Looking for Employment'],
    isOnline: true,
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada', 'Marathi', 'Urdu'],
    matchScore: 95,
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration'
  },

  // --- TRANSPORT & VEHICLES ---
  {
    id: 'SRV-TRANS-024',
    name: 'Sarathi Driving Licence Application, Renewal & Address Change',
    department: 'Ministry of Road Transport & Highways (MoRTH)',
    ministry: 'Ministry of Road Transport & Highways',
    category: 'Transport',
    level: 'Central',
    state: 'All-India',
    description: 'Centralized portal for learner licence online exam, permanent driving licence slot booking, smart card DL renewal, and address change.',
    eligibilitySummary: 'Indian citizen aged 18+ (16+ for gearless 50cc two-wheelers) meeting physical fitness criteria.',
    eligibilityRules: [
      {
        id: 'rule-dl-1',
        field: 'age',
        label: 'Applicant Age',
        type: 'number',
        min: 18,
        explanation: 'Minimum age for motor vehicle with gear is 18 years.',
      }
    ],
    requiredDocuments: ['Aadhaar Card with linked mobile', 'Proof of Age (10th Marksheet / Birth Certificate)', 'Learner Licence Number (for Permanent DL)', 'Medical Certificate Form 1A (if age 40+)'],
    workflowStages: ['Application & Online LL Test', 'Driving Test Slot Booking at RTO', 'Biometrics & Driving Skill Test', 'DL Smart Card Dispatched & DigiLocker Sync'],
    expectedTimeline: '7 - 14 working days post test',
    fee: '₹200 to ₹500 depending on vehicle class',
    officialSource: 'parivahan.gov.in',
    lastVerified: '2026-03-03',
    tags: ['driving licence', 'sarathi', 'rto', 'dl renewal', 'learner licence', 'parivahan'],
    lifeEvents: ['Looking for Employment', 'Relocating / Address Change'],
    isOnline: true,
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada', 'Marathi', 'Bengali'],
    matchScore: 96,
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration'
  },
  {
    id: 'SRV-TRANS-025',
    name: 'Vahan Vehicle Registration Certificate (RC Transfer & NOC)',
    department: 'Ministry of Road Transport & Highways (MoRTH)',
    ministry: 'Ministry of Road Transport & Highways',
    category: 'Transport',
    level: 'Central',
    state: 'All-India',
    description: 'Online management of vehicle ownership transfer, hypothecation termination, duplicate RC, and inter-state NOC via Vahan National Registry.',
    eligibilitySummary: 'Registered vehicle owner or authorized buyer with valid PUC and motor insurance.',
    eligibilityRules: [
      {
        id: 'rule-vahan-1',
        field: 'hasActiveInsurance',
        label: 'Vehicle has active motor insurance policy?',
        type: 'boolean',
        requiredValue: true,
        explanation: 'Active insurance policy verifiable on Vahan API is mandatory.',
      }
    ],
    requiredDocuments: ['Original Registration Certificate (RC)', 'Valid Motor Insurance Certificate', 'Valid Pollution Under Control (PUC)', 'Form 29 & 30 Sale Intimation'],
    workflowStages: ['Online Form Fill & Fee Payment', 'Aadhaar OTP Seller-Buyer Consent', 'RTO Scrutiny', 'Updated RC Issued in DigiLocker'],
    expectedTimeline: '10 - 20 working days',
    fee: '₹150 to ₹500 statutory fee',
    officialSource: 'parivahan.gov.in',
    lastVerified: '2026-02-27',
    tags: ['vehicle registration', 'rc transfer', 'vahan', 'car transfer', 'rto', 'noc'],
    lifeEvents: ['Buying or Building a Home', 'Relocating / Address Change'],
    isOnline: true,
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada'],
    matchScore: 90,
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration'
  },

  // --- IDENTITY & ELECTIONS ---
  {
    id: 'SRV-ELECT-026',
    name: 'National Voter Service (NVSP / e-EPIC Digital Voter ID)',
    department: 'Election Commission of India (ECI)',
    ministry: 'Independent Constitutional Authority',
    category: 'Identity & Certificates',
    level: 'Central',
    state: 'All-India',
    description: 'Register as a new voter (Form 6), update residential constituency (Form 8), and download digitally signed e-EPIC voter card instantly.',
    eligibilitySummary: 'Indian citizen who has attained 18 years of age on the qualifying date.',
    eligibilityRules: [
      {
        id: 'rule-voter-1',
        field: 'age',
        label: 'Applicant Age',
        type: 'number',
        min: 18,
        explanation: 'Must be 18 years or older as per qualifying date.',
      }
    ],
    requiredDocuments: ['Aadhaar Card / Proof of Age', 'Proof of Current Ordinary Residence (Electricity Bill, Water Bill, Aadhaar)'],
    workflowStages: ['Form Submission Online', 'Booth Level Officer (BLO) Field Verification', 'Electoral Registration Officer (ERO) Approval', 'EPIC Generated & e-EPIC PDF Download'],
    expectedTimeline: '14 - 21 working days',
    fee: '₹0 (Free Service)',
    officialSource: 'voters.eci.gov.in',
    lastVerified: '2026-03-05',
    tags: ['voter id', 'epic', 'election', 'nvsp', 'form 6', 'e-epic', 'voting'],
    lifeEvents: ['Starting College', 'Relocating / Address Change'],
    isOnline: true,
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada', 'Malayalam', 'Bengali', 'Marathi', 'Gujarati', 'Punjabi', 'Urdu'],
    matchScore: 97,
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration'
  },
  {
    id: 'SRV-PASSPORT-027',
    name: 'Passport Seva Online Application & PSK Appointment Booking',
    department: 'Consular, Passport and Visa Division (CPV)',
    ministry: 'Ministry of External Affairs',
    category: 'Identity & Certificates',
    level: 'Central',
    state: 'All-India',
    description: 'Direct portal for new passport issuance, passport re-issue, Tatkaal express passports, and Police Clearance Certificate (PCC).',
    eligibilitySummary: 'Indian citizen with verified proof of birth, identity, and present residential address.',
    eligibilityRules: [
      {
        id: 'rule-pass-1',
        field: 'isIndianCitizen',
        label: 'Is applicant a citizen of India by birth or registration?',
        type: 'boolean',
        requiredValue: true,
        explanation: 'Passports are issued only to bona fide Indian citizens.',
      }
    ],
    requiredDocuments: ['Aadhaar Card', 'Proof of Date of Birth (Birth Certificate / 10th Marksheet)', 'Proof of Present Address (Aadhaar / Passbook / Electricity Bill)'],
    workflowStages: ['Online Form Fill & Fee Payment', 'Passport Seva Kendra (PSK) Biometrics Slot', 'Police Physical Address Verification', 'Passport Printed & Delivered by Speed Post'],
    expectedTimeline: '10 - 15 business days (3 days for Tatkaal)',
    fee: '₹1,500 (Standard 36-page passport)',
    officialSource: 'passportindia.gov.in',
    lastVerified: '2026-03-02',
    tags: ['passport', 'passport seva', 'mea', 'psk', 'international travel', 'visa'],
    lifeEvents: ['Starting College', 'Looking for Employment'],
    isOnline: true,
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada', 'Malayalam', 'Punjabi'],
    matchScore: 95,
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration'
  },

  // --- GOVERNMENT GRIEVANCES ---
  {
    id: 'SRV-GRV-028',
    name: 'CPGRAMS Centralized Public Grievance Redress and Monitoring System',
    department: 'Department of Administrative Reforms and Public Grievances (DARPG)',
    ministry: 'Ministry of Personnel, Public Grievances and Pensions',
    category: 'Grievance & Citizen Services',
    level: 'Central',
    state: 'All-India',
    description: 'National 24x7 online platform enabling citizens to lodge grievances against any Central Ministry, State Department, or Public Sector Bank with time-bound resolution and escalation.',
    eligibilitySummary: 'Any citizen having an unresolved service deficiency with a government department or public service agency.',
    eligibilityRules: [
      {
        id: 'rule-grv-1',
        field: 'hasValidContact',
        label: 'Possesses verified mobile number or email address for tracking notifications?',
        type: 'boolean',
        requiredValue: true,
        explanation: 'Status updates and OTP verification are transmitted via mobile/email.',
      }
    ],
    requiredDocuments: ['Grievance description text', 'Supporting order / receipt / correspondence PDF (optional)'],
    workflowStages: ['Grievance Lodged & Registration ID Generated', 'Assigned to Nodal Officer of Department', 'Action Taken & Inquiry Conducted', 'Resolution Uploaded with Citizen Feedback / Appeal'],
    expectedTimeline: '30 days statutory resolution window',
    fee: '₹0 (Free)',
    officialSource: 'pgportal.gov.in',
    lastVerified: '2026-03-05',
    tags: ['grievance', 'complaint', 'cpgrams', 'darpg', 'escalation', 'public service'],
    lifeEvents: ['Starting College', 'Looking for Employment', 'Farmer Support', 'Buying or Building a Home'],
    isOnline: true,
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada', 'Malayalam', 'Bengali', 'Marathi', 'Gujarati', 'Punjabi', 'Urdu'],
    matchScore: 99,
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration'
  },
  {
    id: 'SRV-TEL-029',
    name: 'Sanchar Saathi - CEIR Lost / Stolen Mobile Device Blocking',
    department: 'Department of Telecommunications (DoT)',
    ministry: 'Ministry of Communications',
    category: 'Grievance & Citizen Services',
    level: 'Central',
    state: 'All-India',
    description: 'Directly block lost or stolen mobile IMEI numbers across all telecom operator networks in India to prevent unauthorized use and enable police tracing.',
    eligibilitySummary: 'Any mobile handset owner in India who has filed a Police Lost Property Report / FIR.',
    eligibilityRules: [
      {
        id: 'rule-ceir-1',
        field: 'hasPoliceComplaint',
        label: 'Possesses Police Lost Report or FIR number?',
        type: 'boolean',
        requiredValue: true,
        explanation: 'Police lost intimation number is statutory requirement for CEIR blocking.',
      }
    ],
    requiredDocuments: ['Police Complaint / Lost Report Copy', 'Proof of Mobile Purchase Invoice', 'Identity Proof of Owner'],
    workflowStages: ['Online IMEI Block Request', 'IMEI Blacklisted across all Indian Telecom Towers', 'Handset Tracking Alert Sent to Police', 'Unblock upon Recovery'],
    expectedTimeline: 'Instant (24 hours network blacklist)',
    fee: '₹0 (Free Service)',
    officialSource: 'sancharsaathi.gov.in',
    lastVerified: '2026-03-04',
    tags: ['sanchar saathi', 'ceir', 'lost mobile', 'stolen phone', 'imei block', 'telecom'],
    lifeEvents: ['Relocating / Address Change'],
    isOnline: true,
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada', 'Bengali'],
    matchScore: 95,
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration'
  },

  // --- POWER & RENEWABLES ---
  {
    id: 'SRV-PWR-030',
    name: 'PM Surya Ghar: Muft Bijli Yojana (Rooftop Solar Subsidy up to ₹78,000)',
    department: 'Ministry of Power & MNRE',
    ministry: 'Ministry of New & Renewable Energy',
    category: 'Housing',
    level: 'Central',
    state: 'All-India',
    description: 'Direct government capital subsidy of ₹30,000 to ₹78,000 for residential rooftop solar plant installation with up to 300 units of free monthly solar electricity.',
    eligibilitySummary: 'Residential household with electricity connection and suitable rooftop space.',
    eligibilityRules: [
      {
        id: 'rule-solar-1',
        field: 'hasResidentialMeter',
        label: 'Has active domestic electricity consumer connection?',
        type: 'boolean',
        requiredValue: true,
        explanation: 'Connection must be domestic residential tariff category.',
      }
    ],
    requiredDocuments: ['Electricity Bill (Last 6 Months)', 'Aadhaar Card', 'Rooftop Photo / Feasibility Self-Declaration', 'Bank Account Details for Direct Subsidy'],
    workflowStages: ['Online Registration', 'DISCOM Technical Feasibility Approval', 'Installation by Empanelled Vendor', 'Net-Meter Installation', 'Direct Subsidy DBT to Bank'],
    expectedTimeline: '30 working days',
    fee: 'Subsidized system cost with bank collateral-free loans @ 7%',
    officialSource: 'pmsuryaghar.gov.in',
    lastVerified: '2026-03-03',
    tags: ['solar', 'pm surya ghar', 'free electricity', 'rooftop solar', 'subsidy', 'green energy'],
    lifeEvents: ['Buying or Building a Home'],
    isOnline: true,
    languages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada', 'Marathi', 'Gujarati'],
    matchScore: 94,
    applicationMethod: 'Direct Digital Orchestration',
    integrationStatus: 'Live Integration'
  }
];
